apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: File
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/file
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: test
    filePath: file_path
    identifier: identifier
    name: name
    secretManagerIdentifier: harnessSecretManager
    tags:
    - foo:bar
