apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: SshKey
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: key_tab_file_path
  name: key-tab-file-path
  namespace: crossplane-system
spec:
  forProvider:
    description: test
    identifier: identifier
    kerberos:
    - principal: principal
      realm: realm
      tgtGenerationMethod: KeyTabFilePath
      tgtKeyTabFilePathSpec:
      - keyPath: key_path
    name: name
    port: 22
    tags:
    - foo:bar
