apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/text
  labels:
    testing.upbound.io/example-name: inline
  name: inline
  namespace: crossplane-system
spec:
  forProvider:
    description: example
    identifier: identifier
    name: name
    secretManagerIdentifier: harnessSecretManager
    tags:
    - foo:bar
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline
