apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Winrm
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: account_ntlm
  name: account-ntlm
  namespace: crossplane-system
spec:
  forProvider:
    description: Account-level WinRM with NTLM
    identifier: account_ntlm_v3
    name: Account NTLM v3
    ntlm:
    - domain: example.com
      passwordRef: account.${harness_platform_secret_text.account_ntlm_password.id}
      skipCertCheck: false
      useNoProfile: true
      useSsl: true
      username: admin
    port: 5986
    tags:
    - scope:account
    - auth:ntlm

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: account_kerberos_password_1
  name: account-kerberos-password-1
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for account-level Kerberos
    identifier: account_kerb_pass_20251111
    name: account_kerb_pass_20251111
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: account_ntlm_password
  name: account-ntlm-password
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for account-level NTLM
    identifier: account_ntlm_password_v3
    name: account_ntlm_password_v3
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: org_kerberos_password
  name: org-kerberos-password
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for org-level Kerberos
    identifier: org_kerb_pass_v3
    name: org_kerb_pass_v3
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: org_ntlm_password
  name: org-ntlm-password
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for org-level NTLM
    identifier: org_ntlm_password_v3
    name: org_ntlm_password_v3
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: project_kerberos_password
  name: project-kerberos-password
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for project-level Kerberos
    identifier: proj_kerb_pass_v3
    name: proj_kerb_pass_v3
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline

---

apiVersion: secret.harness.m.crossplane.io/v1alpha1
kind: Text
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/winrm
  labels:
    testing.upbound.io/example-name: project_ntlm_password
  name: project-ntlm-password
  namespace: crossplane-system
spec:
  forProvider:
    description: Password for project-level NTLM
    identifier: proj_ntlm_pass_v3
    name: proj_ntlm_pass_v3
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretManagerIdentifier: harnessSecretManager
    valueSecretRef:
      key: example-key
      name: example-secret
    valueType: Inline
