apiVersion: platform.harness.crossplane.io/v1alpha1
kind: PolicySet
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/policyset
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    action: onrun
    enabled: true
    identifier: harness_platform_policyset.test.identifier
    name: harness_platform_policyset.test.name
    policyReferences:
    - identifier: policy_identifier
      severity: warning
    type: pipeline
