apiVersion: platform.harness.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountId: account_id
    description: test
    email: email@service.harness.io
    identifier: identifier
    name: name
    tags:
    - foo:bar
