apiVersion: cloudprovider.harness.crossplane.io/v1alpha1
kind: Azure
metadata:
  annotations:
    meta.upbound.io/example-id: cloudprovider/v1alpha1/azure
  labels:
    testing.upbound.io/example-name: azure
  name: azure
spec:
  forProvider:
    clientId: <AZURE_CLIENT_ID>
    key: example-secret
    name: azure
    tenantId: <AZURE_TENANT_ID>

---

apiVersion: harness.harness.crossplane.io/v1alpha1
kind: EncryptedText
metadata:
  annotations:
    meta.upbound.io/example-id: cloudprovider/v1alpha1/azure
  labels:
    testing.upbound.io/example-name: azure_key
  name: azure-key
spec:
  forProvider:
    name: azure_key
    secretManagerId: ${data.harness_secret_manager.default.id}
    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
