// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HealthInitParameters struct {

	// (String) API path to use for health check
	// API path to use for health check
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Health check port on the VM
	// Health check port on the VM
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol can be http or https
	// Protocol can be http or https
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (Number) Lower limit for acceptable status code
	// Lower limit for acceptable status code
	StatusCodeFrom *float64 `json:"statusCodeFrom,omitempty" tf:"status_code_from,omitempty"`

	// (Number) Upper limit for acceptable status code
	// Upper limit for acceptable status code
	StatusCodeTo *float64 `json:"statusCodeTo,omitempty" tf:"status_code_to,omitempty"`

	// (Number) Health check timeout
	// Health check timeout
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type HealthObservation struct {

	// (String) API path to use for health check
	// API path to use for health check
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Health check port on the VM
	// Health check port on the VM
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol can be http or https
	// Protocol can be http or https
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (Number) Lower limit for acceptable status code
	// Lower limit for acceptable status code
	StatusCodeFrom *float64 `json:"statusCodeFrom,omitempty" tf:"status_code_from,omitempty"`

	// (Number) Upper limit for acceptable status code
	// Upper limit for acceptable status code
	StatusCodeTo *float64 `json:"statusCodeTo,omitempty" tf:"status_code_to,omitempty"`

	// (Number) Health check timeout
	// Health check timeout
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type HealthParameters struct {

	// (String) API path to use for health check
	// API path to use for health check
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Health check port on the VM
	// Health check port on the VM
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// (String) Protocol can be http or https
	// Protocol can be http or https
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// (Number) Lower limit for acceptable status code
	// Lower limit for acceptable status code
	// +kubebuilder:validation:Optional
	StatusCodeFrom *float64 `json:"statusCodeFrom,omitempty" tf:"status_code_from,omitempty"`

	// (Number) Upper limit for acceptable status code
	// Upper limit for acceptable status code
	// +kubebuilder:validation:Optional
	StatusCodeTo *float64 `json:"statusCodeTo,omitempty" tf:"status_code_to,omitempty"`

	// (Number) Health check timeout
	// Health check timeout
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type RoutingInitParameters struct {

	// (String) Action to take for the routing rule
	// Action to take for the routing rule
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) API path to use for health check
	// Path to use for the proxy
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Port on the proxy
	// Port on the proxy
	SourcePort *float64 `json:"sourcePort,omitempty" tf:"source_port,omitempty"`

	// (String) Source protocol of the proxy can be http or https
	// Source protocol of the proxy can be http or https
	SourceProtocol *string `json:"sourceProtocol,omitempty" tf:"source_protocol,omitempty"`

	// (Number) Port on the VM
	// Port on the VM
	TargetPort *float64 `json:"targetPort,omitempty" tf:"target_port,omitempty"`

	// (String) Target protocol of the instance can be http or https
	// Target protocol of the instance can be http or https
	TargetProtocol *string `json:"targetProtocol,omitempty" tf:"target_protocol,omitempty"`
}

type RoutingObservation struct {

	// (String) Action to take for the routing rule
	// Action to take for the routing rule
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) API path to use for health check
	// Path to use for the proxy
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Port on the proxy
	// Port on the proxy
	SourcePort *float64 `json:"sourcePort,omitempty" tf:"source_port,omitempty"`

	// (String) Source protocol of the proxy can be http or https
	// Source protocol of the proxy can be http or https
	SourceProtocol *string `json:"sourceProtocol,omitempty" tf:"source_protocol,omitempty"`

	// (Number) Port on the VM
	// Port on the VM
	TargetPort *float64 `json:"targetPort,omitempty" tf:"target_port,omitempty"`

	// (String) Target protocol of the instance can be http or https
	// Target protocol of the instance can be http or https
	TargetProtocol *string `json:"targetProtocol,omitempty" tf:"target_protocol,omitempty"`
}

type RoutingParameters struct {

	// (String) Action to take for the routing rule
	// Action to take for the routing rule
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) API path to use for health check
	// Path to use for the proxy
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Port on the proxy
	// Port on the proxy
	// +kubebuilder:validation:Optional
	SourcePort *float64 `json:"sourcePort,omitempty" tf:"source_port,omitempty"`

	// (String) Source protocol of the proxy can be http or https
	// Source protocol of the proxy can be http or https
	// +kubebuilder:validation:Optional
	SourceProtocol *string `json:"sourceProtocol" tf:"source_protocol,omitempty"`

	// (Number) Port on the VM
	// Port on the VM
	// +kubebuilder:validation:Optional
	TargetPort *float64 `json:"targetPort,omitempty" tf:"target_port,omitempty"`

	// (String) Target protocol of the instance can be http or https
	// Target protocol of the instance can be http or https
	// +kubebuilder:validation:Optional
	TargetProtocol *string `json:"targetProtocol" tf:"target_protocol,omitempty"`
}

type RuleScaleGroupDependsInitParameters struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	RuleID *float64 `json:"ruleId,omitempty" tf:"rule_id,omitempty"`
}

type RuleScaleGroupDependsObservation struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	RuleID *float64 `json:"ruleId,omitempty" tf:"rule_id,omitempty"`
}

type RuleScaleGroupDependsParameters struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	// +kubebuilder:validation:Optional
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	// +kubebuilder:validation:Optional
	RuleID *float64 `json:"ruleId" tf:"rule_id,omitempty"`
}

type RuleScaleGroupHTTPInitParameters struct {

	// (Block List) Health Check Details (see below for nested schema)
	// Health Check Details
	Health []HealthInitParameters `json:"health,omitempty" tf:"health,omitempty"`

	// (String) Id of the proxy
	// Id of the proxy
	ProxyID *string `json:"proxyId,omitempty" tf:"proxy_id,omitempty"`

	// (Block List) Routing configuration used to access the scaling group (see below for nested schema)
	// Routing configuration used to access the scaling group
	Routing []RoutingInitParameters `json:"routing,omitempty" tf:"routing,omitempty"`
}

type RuleScaleGroupHTTPObservation struct {

	// (Block List) Health Check Details (see below for nested schema)
	// Health Check Details
	Health []HealthObservation `json:"health,omitempty" tf:"health,omitempty"`

	// (String) Id of the proxy
	// Id of the proxy
	ProxyID *string `json:"proxyId,omitempty" tf:"proxy_id,omitempty"`

	// (Block List) Routing configuration used to access the scaling group (see below for nested schema)
	// Routing configuration used to access the scaling group
	Routing []RoutingObservation `json:"routing,omitempty" tf:"routing,omitempty"`
}

type RuleScaleGroupHTTPParameters struct {

	// (Block List) Health Check Details (see below for nested schema)
	// Health Check Details
	// +kubebuilder:validation:Optional
	Health []HealthParameters `json:"health,omitempty" tf:"health,omitempty"`

	// (String) Id of the proxy
	// Id of the proxy
	// +kubebuilder:validation:Optional
	ProxyID *string `json:"proxyId" tf:"proxy_id,omitempty"`

	// (Block List) Routing configuration used to access the scaling group (see below for nested schema)
	// Routing configuration used to access the scaling group
	// +kubebuilder:validation:Optional
	Routing []RoutingParameters `json:"routing,omitempty" tf:"routing,omitempty"`
}

type RuleScaleGroupInitParameters struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (List of String) Custom URLs used to access the instances
	// Custom URLs used to access the instances
	CustomDomains []*string `json:"customDomains,omitempty" tf:"custom_domains,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	Depends []RuleScaleGroupDependsInitParameters `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Block List) Http routing configuration (see below for nested schema)
	// Http routing configuration
	HTTP []RuleScaleGroupHTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Min: 1, Max: 1) Scaling Group configuration (see below for nested schema)
	// Scaling Group configuration
	ScaleGroup []ScaleGroupInitParameters `json:"scaleGroup,omitempty" tf:"scale_group,omitempty"`
}

type RuleScaleGroupObservation struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (List of String) Custom URLs used to access the instances
	// Custom URLs used to access the instances
	CustomDomains []*string `json:"customDomains,omitempty" tf:"custom_domains,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	Depends []RuleScaleGroupDependsObservation `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Block List) Http routing configuration (see below for nested schema)
	// Http routing configuration
	HTTP []RuleScaleGroupHTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Min: 1, Max: 1) Scaling Group configuration (see below for nested schema)
	// Scaling Group configuration
	ScaleGroup []ScaleGroupObservation `json:"scaleGroup,omitempty" tf:"scale_group,omitempty"`
}

type RuleScaleGroupParameters struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	// +kubebuilder:validation:Optional
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (List of String) Custom URLs used to access the instances
	// Custom URLs used to access the instances
	// +kubebuilder:validation:Optional
	CustomDomains []*string `json:"customDomains,omitempty" tf:"custom_domains,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	// +kubebuilder:validation:Optional
	Depends []RuleScaleGroupDependsParameters `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Block List) Http routing configuration (see below for nested schema)
	// Http routing configuration
	// +kubebuilder:validation:Optional
	HTTP []RuleScaleGroupHTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// +kubebuilder:validation:Optional
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Min: 1, Max: 1) Scaling Group configuration (see below for nested schema)
	// Scaling Group configuration
	// +kubebuilder:validation:Optional
	ScaleGroup []ScaleGroupParameters `json:"scaleGroup,omitempty" tf:"scale_group,omitempty"`
}

type ScaleGroupInitParameters struct {

	// (Number) Desired capacity of the Scaling Group
	// Desired capacity of the Scaling Group
	Desired *float64 `json:"desired,omitempty" tf:"desired,omitempty"`

	// (String) The ID of this resource.
	// ID of the Scaling Group
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Maximum capacity of the Scaling Group
	// Maximum capacity of the Scaling Group
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// (Number) Minimum capacity of the Scaling Group
	// Minimum capacity of the Scaling Group
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// (String) Name of the rule
	// Name of the Scaling Group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// demand capacity of the Scaling Group
	// On-demand capacity of the Scaling Group
	OnDemand *float64 `json:"onDemand,omitempty" tf:"on_demand,omitempty"`

	// (String) Region of the Scaling Group
	// Region of the Scaling Group
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Zone of the Scaling Group. Needed for GCP only
	// Zone of the Scaling Group. Needed for GCP only
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ScaleGroupObservation struct {

	// (Number) Desired capacity of the Scaling Group
	// Desired capacity of the Scaling Group
	Desired *float64 `json:"desired,omitempty" tf:"desired,omitempty"`

	// (String) The ID of this resource.
	// ID of the Scaling Group
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Maximum capacity of the Scaling Group
	// Maximum capacity of the Scaling Group
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// (Number) Minimum capacity of the Scaling Group
	// Minimum capacity of the Scaling Group
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// (String) Name of the rule
	// Name of the Scaling Group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// demand capacity of the Scaling Group
	// On-demand capacity of the Scaling Group
	OnDemand *float64 `json:"onDemand,omitempty" tf:"on_demand,omitempty"`

	// (String) Region of the Scaling Group
	// Region of the Scaling Group
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Zone of the Scaling Group. Needed for GCP only
	// Zone of the Scaling Group. Needed for GCP only
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ScaleGroupParameters struct {

	// (Number) Desired capacity of the Scaling Group
	// Desired capacity of the Scaling Group
	// +kubebuilder:validation:Optional
	Desired *float64 `json:"desired" tf:"desired,omitempty"`

	// (String) The ID of this resource.
	// ID of the Scaling Group
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (Number) Maximum capacity of the Scaling Group
	// Maximum capacity of the Scaling Group
	// +kubebuilder:validation:Optional
	Max *float64 `json:"max" tf:"max,omitempty"`

	// (Number) Minimum capacity of the Scaling Group
	// Minimum capacity of the Scaling Group
	// +kubebuilder:validation:Optional
	Min *float64 `json:"min" tf:"min,omitempty"`

	// (String) Name of the rule
	// Name of the Scaling Group
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// demand capacity of the Scaling Group
	// On-demand capacity of the Scaling Group
	// +kubebuilder:validation:Optional
	OnDemand *float64 `json:"onDemand" tf:"on_demand,omitempty"`

	// (String) Region of the Scaling Group
	// Region of the Scaling Group
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Zone of the Scaling Group. Needed for GCP only
	// Zone of the Scaling Group. Needed for GCP only
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// RuleScaleGroupSpec defines the desired state of RuleScaleGroup
type RuleScaleGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RuleScaleGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleScaleGroupInitParameters `json:"initProvider,omitempty"`
}

// RuleScaleGroupStatus defines the observed state of RuleScaleGroup.
type RuleScaleGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleScaleGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleScaleGroup is the Schema for the RuleScaleGroups API. Resource for creating a Harness AutoStopping rule for Scaling Groups.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type RuleScaleGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudConnectorId) || (has(self.initProvider) && has(self.initProvider.cloudConnectorId))",message="spec.forProvider.cloudConnectorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scaleGroup) || (has(self.initProvider) && has(self.initProvider.scaleGroup))",message="spec.forProvider.scaleGroup is a required parameter"
	Spec   RuleScaleGroupSpec   `json:"spec"`
	Status RuleScaleGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleScaleGroupList contains a list of RuleScaleGroups
type RuleScaleGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleScaleGroup `json:"items"`
}

// Repository type metadata.
var (
	RuleScaleGroup_Kind             = "RuleScaleGroup"
	RuleScaleGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleScaleGroup_Kind}.String()
	RuleScaleGroup_KindAPIVersion   = RuleScaleGroup_Kind + "." + CRDGroupVersion.String()
	RuleScaleGroup_GroupVersionKind = CRDGroupVersion.WithKind(RuleScaleGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleScaleGroup{}, &RuleScaleGroupList{})
}
