// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DatacenterInitParameters struct {

	// (String) The name of the cloud provider.
	// The name of the cloud provider.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) This block is used for scoping the resource to a specific set of applications or environments. (see below for nested schema)
	// This block is used for scoping the resource to a specific set of applications or environments.
	UsageScope []DatacenterUsageScopeInitParameters `json:"usageScope,omitempty" tf:"usage_scope,omitempty"`
}

type DatacenterObservation struct {

	// (String) The id of the cloud provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the cloud provider.
	// The name of the cloud provider.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) This block is used for scoping the resource to a specific set of applications or environments. (see below for nested schema)
	// This block is used for scoping the resource to a specific set of applications or environments.
	UsageScope []DatacenterUsageScopeObservation `json:"usageScope,omitempty" tf:"usage_scope,omitempty"`
}

type DatacenterParameters struct {

	// (String) The name of the cloud provider.
	// The name of the cloud provider.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) This block is used for scoping the resource to a specific set of applications or environments. (see below for nested schema)
	// This block is used for scoping the resource to a specific set of applications or environments.
	// +kubebuilder:validation:Optional
	UsageScope []DatacenterUsageScopeParameters `json:"usageScope,omitempty" tf:"usage_scope,omitempty"`
}

type DatacenterUsageScopeInitParameters struct {

	// (String) Id of the application to scope to. If empty then this scope applies to all applications.
	// Id of the application to scope to. If empty then this scope applies to all applications.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// (String) Type of environment filter applied. Cannot be used with environment_id. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	// Type of environment filter applied. Cannot be used with `environment_id`. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	EnvironmentFilterType *string `json:"environmentFilterType,omitempty" tf:"environment_filter_type,omitempty"`

	// (String) Id of the id of the specific environment to scope to. Cannot be used with environment_filter_type.
	// Id of the id of the specific environment to scope to. Cannot be used with `environment_filter_type`.
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`
}

type DatacenterUsageScopeObservation struct {

	// (String) Id of the application to scope to. If empty then this scope applies to all applications.
	// Id of the application to scope to. If empty then this scope applies to all applications.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// (String) Type of environment filter applied. Cannot be used with environment_id. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	// Type of environment filter applied. Cannot be used with `environment_id`. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	EnvironmentFilterType *string `json:"environmentFilterType,omitempty" tf:"environment_filter_type,omitempty"`

	// (String) Id of the id of the specific environment to scope to. Cannot be used with environment_filter_type.
	// Id of the id of the specific environment to scope to. Cannot be used with `environment_filter_type`.
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`
}

type DatacenterUsageScopeParameters struct {

	// (String) Id of the application to scope to. If empty then this scope applies to all applications.
	// Id of the application to scope to. If empty then this scope applies to all applications.
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// (String) Type of environment filter applied. Cannot be used with environment_id. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	// Type of environment filter applied. Cannot be used with `environment_id`. Valid options are NON_PRODUCTION_ENVIRONMENTS, PRODUCTION_ENVIRONMENTS.
	// +kubebuilder:validation:Optional
	EnvironmentFilterType *string `json:"environmentFilterType,omitempty" tf:"environment_filter_type,omitempty"`

	// (String) Id of the id of the specific environment to scope to. Cannot be used with environment_filter_type.
	// Id of the id of the specific environment to scope to. Cannot be used with `environment_filter_type`.
	// +kubebuilder:validation:Optional
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`
}

// DatacenterSpec defines the desired state of Datacenter
type DatacenterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatacenterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatacenterInitParameters `json:"initProvider,omitempty"`
}

// DatacenterStatus defines the observed state of Datacenter.
type DatacenterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatacenterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Datacenter is the Schema for the Datacenters API. Resource for creating a physical data center cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type Datacenter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DatacenterSpec   `json:"spec"`
	Status DatacenterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatacenterList contains a list of Datacenters
type DatacenterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Datacenter `json:"items"`
}

// Repository type metadata.
var (
	Datacenter_Kind             = "Datacenter"
	Datacenter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Datacenter_Kind}.String()
	Datacenter_KindAPIVersion   = Datacenter_Kind + "." + CRDGroupVersion.String()
	Datacenter_GroupVersionKind = CRDGroupVersion.WithKind(Datacenter_Kind)
)

func init() {
	SchemeBuilder.Register(&Datacenter{}, &DatacenterList{})
}
