// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AwsProxyInitParameters struct {

	// (String, Sensitive) Harness NG API key
	// Harness NG API key
	APIKeySecretRef v1.SecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// (Boolean) Boolean value to indicate if proxy vm needs to have static IP
	// Boolean value to indicate if proxy vm needs to have static IP
	AllocateStaticIP *bool `json:"allocateStaticIp,omitempty" tf:"allocate_static_ip,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Certificates []CertificatesInitParameters `json:"certificates,omitempty" tf:"certificates,omitempty"`

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself. When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself.
	DeleteCloudResourcesOnDestroy *bool `json:"deleteCloudResourcesOnDestroy,omitempty" tf:"delete_cloud_resources_on_destroy,omitempty"`

	// (String)
	Keypair *string `json:"keypair,omitempty" tf:"keypair,omitempty"`

	// (String) Machine instance type
	// Machine instance type
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// (String) Name of the proxy
	// Name of the proxy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Region in which cloud resources are hosted
	// Region in which cloud resources are hosted
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (List of String) Security Group to define the security rules that determine the inbound and outbound traffic
	// Security Group to define the security rules that determine the inbound and outbound traffic
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) VPC in which cloud resources are hosted
	// VPC in which cloud resources are hosted
	VPC *string `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type AwsProxyObservation struct {

	// (Boolean) Boolean value to indicate if proxy vm needs to have static IP
	// Boolean value to indicate if proxy vm needs to have static IP
	AllocateStaticIP *bool `json:"allocateStaticIp,omitempty" tf:"allocate_static_ip,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Certificates []CertificatesObservation `json:"certificates,omitempty" tf:"certificates,omitempty"`

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself. When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself.
	DeleteCloudResourcesOnDestroy *bool `json:"deleteCloudResourcesOnDestroy,omitempty" tf:"delete_cloud_resources_on_destroy,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String)
	Keypair *string `json:"keypair,omitempty" tf:"keypair,omitempty"`

	// (String) Machine instance type
	// Machine instance type
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// (String) Name of the proxy
	// Name of the proxy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Private IP address of the proxy
	// Private IP address of the proxy
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// (String) Public IP address of the proxy
	// Public IP address of the proxy
	PublicIP *string `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// (String) Region in which cloud resources are hosted
	// Region in which cloud resources are hosted
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (List of String) Security Group to define the security rules that determine the inbound and outbound traffic
	// Security Group to define the security rules that determine the inbound and outbound traffic
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) VPC in which cloud resources are hosted
	// VPC in which cloud resources are hosted
	VPC *string `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type AwsProxyParameters struct {

	// (String, Sensitive) Harness NG API key
	// Harness NG API key
	// +kubebuilder:validation:Optional
	APIKeySecretRef v1.SecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// (Boolean) Boolean value to indicate if proxy vm needs to have static IP
	// Boolean value to indicate if proxy vm needs to have static IP
	// +kubebuilder:validation:Optional
	AllocateStaticIP *bool `json:"allocateStaticIp,omitempty" tf:"allocate_static_ip,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Certificates []CertificatesParameters `json:"certificates,omitempty" tf:"certificates,omitempty"`

	// (String) Id of the cloud connector
	// Id of the cloud connector
	// +kubebuilder:validation:Optional
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself. When set to true, the associated VM will be deleted permanently from AWS account. Be fully aware of the consequneces of settting this to true, as the action is irreversible. When set to false, solely the Harness LB representation will be deleted, which leaves the proxy VM in AWS account itself.
	// +kubebuilder:validation:Optional
	DeleteCloudResourcesOnDestroy *bool `json:"deleteCloudResourcesOnDestroy,omitempty" tf:"delete_cloud_resources_on_destroy,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Keypair *string `json:"keypair,omitempty" tf:"keypair,omitempty"`

	// (String) Machine instance type
	// Machine instance type
	// +kubebuilder:validation:Optional
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// (String) Name of the proxy
	// Name of the proxy
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Region in which cloud resources are hosted
	// Region in which cloud resources are hosted
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (List of String) Security Group to define the security rules that determine the inbound and outbound traffic
	// Security Group to define the security rules that determine the inbound and outbound traffic
	// +kubebuilder:validation:Optional
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) VPC in which cloud resources are hosted
	// VPC in which cloud resources are hosted
	// +kubebuilder:validation:Optional
	VPC *string `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type CertificatesInitParameters struct {

	// (String) Certificate secret ID
	// Certificate secret ID
	CertSecretID *string `json:"certSecretId,omitempty" tf:"cert_secret_id,omitempty"`

	// (String) Private key secret ID
	// Private key secret ID
	KeySecretID *string `json:"keySecretId,omitempty" tf:"key_secret_id,omitempty"`
}

type CertificatesObservation struct {

	// (String) Certificate secret ID
	// Certificate secret ID
	CertSecretID *string `json:"certSecretId,omitempty" tf:"cert_secret_id,omitempty"`

	// (String) Private key secret ID
	// Private key secret ID
	KeySecretID *string `json:"keySecretId,omitempty" tf:"key_secret_id,omitempty"`
}

type CertificatesParameters struct {

	// (String) Certificate secret ID
	// Certificate secret ID
	// +kubebuilder:validation:Optional
	CertSecretID *string `json:"certSecretId" tf:"cert_secret_id,omitempty"`

	// (String) Private key secret ID
	// Private key secret ID
	// +kubebuilder:validation:Optional
	KeySecretID *string `json:"keySecretId" tf:"key_secret_id,omitempty"`
}

// AwsProxySpec defines the desired state of AwsProxy
type AwsProxySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AwsProxyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AwsProxyInitParameters `json:"initProvider,omitempty"`
}

// AwsProxyStatus defines the observed state of AwsProxy.
type AwsProxyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AwsProxyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AwsProxy is the Schema for the AwsProxys API. Resource for creating an AWS Autostopping proxy
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type AwsProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiKeySecretRef)",message="spec.forProvider.apiKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudConnectorId) || (has(self.initProvider) && has(self.initProvider.cloudConnectorId))",message="spec.forProvider.cloudConnectorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deleteCloudResourcesOnDestroy) || (has(self.initProvider) && has(self.initProvider.deleteCloudResourcesOnDestroy))",message="spec.forProvider.deleteCloudResourcesOnDestroy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.machineType) || (has(self.initProvider) && has(self.initProvider.machineType))",message="spec.forProvider.machineType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpc) || (has(self.initProvider) && has(self.initProvider.vpc))",message="spec.forProvider.vpc is a required parameter"
	Spec   AwsProxySpec   `json:"spec"`
	Status AwsProxyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AwsProxyList contains a list of AwsProxys
type AwsProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AwsProxy `json:"items"`
}

// Repository type metadata.
var (
	AwsProxy_Kind             = "AwsProxy"
	AwsProxy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AwsProxy_Kind}.String()
	AwsProxy_KindAPIVersion   = AwsProxy_Kind + "." + CRDGroupVersion.String()
	AwsProxy_GroupVersionKind = CRDGroupVersion.WithKind(AwsProxy_Kind)
)

func init() {
	SchemeBuilder.Register(&AwsProxy{}, &AwsProxyList{})
}
