// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RuleK8sDependsInitParameters struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	RuleID *float64 `json:"ruleId,omitempty" tf:"rule_id,omitempty"`
}

type RuleK8sDependsObservation struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	RuleID *float64 `json:"ruleId,omitempty" tf:"rule_id,omitempty"`
}

type RuleK8sDependsParameters struct {

	// (Number) Number of seconds the rule should wait after warming up the dependent rule
	// Number of seconds the rule should wait after warming up the dependent rule
	// +kubebuilder:validation:Optional
	DelayInSec *float64 `json:"delayInSec,omitempty" tf:"delay_in_sec,omitempty"`

	// (Number) Rule id of the dependent rule
	// Rule id of the dependent rule
	// +kubebuilder:validation:Optional
	RuleID *float64 `json:"ruleId" tf:"rule_id,omitempty"`
}

type RuleK8sInitParameters struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	Depends []RuleK8sDependsInitParameters `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Id of the K8s connector
	// Id of the K8s connector
	K8SConnectorID *string `json:"k8sConnectorId,omitempty" tf:"k8s_connector_id,omitempty"`

	// (String) Namespace of the cluster
	// Namespace of the cluster
	K8SNamespace *string `json:"k8sNamespace,omitempty" tf:"k8s_namespace,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	// YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	RuleYaml *string `json:"ruleYaml,omitempty" tf:"rule_yaml,omitempty"`
}

type RuleK8sObservation struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	Depends []RuleK8sDependsObservation `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Id of the K8s connector
	// Id of the K8s connector
	K8SConnectorID *string `json:"k8sConnectorId,omitempty" tf:"k8s_connector_id,omitempty"`

	// (String) Namespace of the cluster
	// Namespace of the cluster
	K8SNamespace *string `json:"k8sNamespace,omitempty" tf:"k8s_namespace,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	// YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	RuleYaml *string `json:"ruleYaml,omitempty" tf:"rule_yaml,omitempty"`
}

type RuleK8sParameters struct {

	// (String) Id of the cloud connector
	// Id of the cloud connector
	// +kubebuilder:validation:Optional
	CloudConnectorID *string `json:"cloudConnectorId,omitempty" tf:"cloud_connector_id,omitempty"`

	// (Block List) Dependent rules (see below for nested schema)
	// Dependent rules
	// +kubebuilder:validation:Optional
	Depends []RuleK8sDependsParameters `json:"depends,omitempty" tf:"depends,omitempty"`

	// (Boolean) Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// Boolean that indicates whether the AutoStopping rule should be created in DryRun mode
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Number) Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// Idle time in minutes. This is the time that the AutoStopping rule waits before stopping the idle instances.
	// +kubebuilder:validation:Optional
	IdleTimeMins *float64 `json:"idleTimeMins,omitempty" tf:"idle_time_mins,omitempty"`

	// (String) Id of the K8s connector
	// Id of the K8s connector
	// +kubebuilder:validation:Optional
	K8SConnectorID *string `json:"k8sConnectorId,omitempty" tf:"k8s_connector_id,omitempty"`

	// (String) Namespace of the cluster
	// Namespace of the cluster
	// +kubebuilder:validation:Optional
	K8SNamespace *string `json:"k8sNamespace,omitempty" tf:"k8s_namespace,omitempty"`

	// (String) Name of the rule
	// Name of the rule
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	// YAML definition of the K8s AutoStopping rule (workload selector, ingress, etc.).
	// +kubebuilder:validation:Optional
	RuleYaml *string `json:"ruleYaml,omitempty" tf:"rule_yaml,omitempty"`
}

// RuleK8sSpec defines the desired state of RuleK8s
type RuleK8sSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleK8sParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleK8sInitParameters `json:"initProvider,omitempty"`
}

// RuleK8sStatus defines the observed state of RuleK8s.
type RuleK8sStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleK8sObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleK8s is the Schema for the RuleK8ss API. Data source for retrieving a Harness AutoStopping rule for K8s services.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type RuleK8s struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudConnectorId) || (has(self.initProvider) && has(self.initProvider.cloudConnectorId))",message="spec.forProvider.cloudConnectorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.k8sConnectorId) || (has(self.initProvider) && has(self.initProvider.k8sConnectorId))",message="spec.forProvider.k8sConnectorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.k8sNamespace) || (has(self.initProvider) && has(self.initProvider.k8sNamespace))",message="spec.forProvider.k8sNamespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ruleYaml) || (has(self.initProvider) && has(self.initProvider.ruleYaml))",message="spec.forProvider.ruleYaml is a required parameter"
	Spec   RuleK8sSpec   `json:"spec"`
	Status RuleK8sStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleK8sList contains a list of RuleK8ss
type RuleK8sList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleK8s `json:"items"`
}

// Repository type metadata.
var (
	RuleK8s_Kind             = "RuleK8s"
	RuleK8s_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleK8s_Kind}.String()
	RuleK8s_KindAPIVersion   = RuleK8s_Kind + "." + CRDGroupVersion.String()
	RuleK8s_GroupVersionKind = CRDGroupVersion.WithKind(RuleK8s_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleK8s{}, &RuleK8sList{})
}
