apiVersion: harness.harness.m.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: harness/v1alpha1/application
  labels:
    testing.upbound.io/example-name: myapp
  name: myapp
  namespace: crossplane-system
spec:
  forProvider:
    description: This is my first Harness application
    name: My Application
    tags:
    - mytag:myvalue
    - team:development
