apiVersion: harness.harness.m.crossplane.io/v1alpha1
kind: SshCredential
metadata:
  annotations:
    meta.upbound.io/example-id: harness/v1alpha1/sshcredential
  labels:
    testing.upbound.io/example-name: ssh_creds
  name: ssh-creds
  namespace: crossplane-system
spec:
  forProvider:
    name: ssh-test
    sshAuthentication:
    - inlineSsh:
      - sshKeyFileId: ${harness_encrypted_text.my_secret.id}
      port: 22
      username: git

---

apiVersion: harness.harness.m.crossplane.io/v1alpha1
kind: EncryptedText
metadata:
  annotations:
    meta.upbound.io/example-id: harness/v1alpha1/sshcredential
  labels:
    testing.upbound.io/example-name: my_secret
  name: my-secret
  namespace: crossplane-system
spec:
  forProvider:
    name: my_secret
    secretManagerId: ${data.harness_secret_manager.secret_manager.id}
    valueSecretRef:
      key: attribute.private_key_pem
      name: example-private-key
