// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AwsAMIInitParameters struct {

	// (String) The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	// The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	AMIDeploymentType *string `json:"amiDeploymentType,omitempty" tf:"ami_deployment_type,omitempty"`

	// (Boolean) Flag to indicate whether the autoscaling group identifies the workload.
	// Flag to indicate whether the autoscaling group identifies the workload.
	AsgIdentifiesWorkload *bool `json:"asgIdentifiesWorkload,omitempty" tf:"asg_identifies_workload,omitempty"`

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (Set of String) The classic load balancers to use.
	// The classic load balancers to use.
	// +listType=set
	ClassicLoadbalancers []*string `json:"classicLoadbalancers,omitempty" tf:"classic_loadbalancers,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The name of the SpotInst cloud provider to connect with.
	// The name of the SpotInst cloud provider to connect with.
	SpotinstCloudProviderName *string `json:"spotinstCloudProviderName,omitempty" tf:"spotinst_cloud_provider_name,omitempty"`

	// (String) The SpotInst configuration to use.
	// The SpotInst configuration to use.
	SpotinstConfigJSON *string `json:"spotinstConfigJson,omitempty" tf:"spotinst_config_json,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +listType=set
	StageClassicLoadbalancers []*string `json:"stageClassicLoadbalancers,omitempty" tf:"stage_classic_loadbalancers,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +listType=set
	StageTargetGroupArns []*string `json:"stageTargetGroupArns,omitempty" tf:"stage_target_group_arns,omitempty"`

	// (Set of String) The ARN's of the target groups.
	// The ARN's of the target groups.
	// +listType=set
	TargetGroupArns []*string `json:"targetGroupArns,omitempty" tf:"target_group_arns,omitempty"`

	// (Boolean) Flag to enable traffic shifting.
	// Flag to enable traffic shifting.
	UseTrafficShift *bool `json:"useTrafficShift,omitempty" tf:"use_traffic_shift,omitempty"`
}

type AwsAMIObservation struct {

	// (String) The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	// The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	AMIDeploymentType *string `json:"amiDeploymentType,omitempty" tf:"ami_deployment_type,omitempty"`

	// (Boolean) Flag to indicate whether the autoscaling group identifies the workload.
	// Flag to indicate whether the autoscaling group identifies the workload.
	AsgIdentifiesWorkload *bool `json:"asgIdentifiesWorkload,omitempty" tf:"asg_identifies_workload,omitempty"`

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (Set of String) The classic load balancers to use.
	// The classic load balancers to use.
	// +listType=set
	ClassicLoadbalancers []*string `json:"classicLoadbalancers,omitempty" tf:"classic_loadbalancers,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The name of the SpotInst cloud provider to connect with.
	// The name of the SpotInst cloud provider to connect with.
	SpotinstCloudProviderName *string `json:"spotinstCloudProviderName,omitempty" tf:"spotinst_cloud_provider_name,omitempty"`

	// (String) The SpotInst configuration to use.
	// The SpotInst configuration to use.
	SpotinstConfigJSON *string `json:"spotinstConfigJson,omitempty" tf:"spotinst_config_json,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +listType=set
	StageClassicLoadbalancers []*string `json:"stageClassicLoadbalancers,omitempty" tf:"stage_classic_loadbalancers,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +listType=set
	StageTargetGroupArns []*string `json:"stageTargetGroupArns,omitempty" tf:"stage_target_group_arns,omitempty"`

	// (Set of String) The ARN's of the target groups.
	// The ARN's of the target groups.
	// +listType=set
	TargetGroupArns []*string `json:"targetGroupArns,omitempty" tf:"target_group_arns,omitempty"`

	// (Boolean) Flag to enable traffic shifting.
	// Flag to enable traffic shifting.
	UseTrafficShift *bool `json:"useTrafficShift,omitempty" tf:"use_traffic_shift,omitempty"`
}

type AwsAMIParameters struct {

	// (String) The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	// The ami deployment type to use. Valid options are AWS_ASG, SPOTINST
	// +kubebuilder:validation:Optional
	AMIDeploymentType *string `json:"amiDeploymentType" tf:"ami_deployment_type,omitempty"`

	// (Boolean) Flag to indicate whether the autoscaling group identifies the workload.
	// Flag to indicate whether the autoscaling group identifies the workload.
	// +kubebuilder:validation:Optional
	AsgIdentifiesWorkload *bool `json:"asgIdentifiesWorkload,omitempty" tf:"asg_identifies_workload,omitempty"`

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	// +kubebuilder:validation:Optional
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (Set of String) The classic load balancers to use.
	// The classic load balancers to use.
	// +kubebuilder:validation:Optional
	// +listType=set
	ClassicLoadbalancers []*string `json:"classicLoadbalancers,omitempty" tf:"classic_loadbalancers,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	// +kubebuilder:validation:Optional
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// (String) The name of the SpotInst cloud provider to connect with.
	// The name of the SpotInst cloud provider to connect with.
	// +kubebuilder:validation:Optional
	SpotinstCloudProviderName *string `json:"spotinstCloudProviderName,omitempty" tf:"spotinst_cloud_provider_name,omitempty"`

	// (String) The SpotInst configuration to use.
	// The SpotInst configuration to use.
	// +kubebuilder:validation:Optional
	SpotinstConfigJSON *string `json:"spotinstConfigJson,omitempty" tf:"spotinst_config_json,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +kubebuilder:validation:Optional
	// +listType=set
	StageClassicLoadbalancers []*string `json:"stageClassicLoadbalancers,omitempty" tf:"stage_classic_loadbalancers,omitempty"`

	// (Set of String) The staging classic load balancers to use.
	// The staging classic load balancers to use.
	// +kubebuilder:validation:Optional
	// +listType=set
	StageTargetGroupArns []*string `json:"stageTargetGroupArns,omitempty" tf:"stage_target_group_arns,omitempty"`

	// (Set of String) The ARN's of the target groups.
	// The ARN's of the target groups.
	// +kubebuilder:validation:Optional
	// +listType=set
	TargetGroupArns []*string `json:"targetGroupArns,omitempty" tf:"target_group_arns,omitempty"`

	// (Boolean) Flag to enable traffic shifting.
	// Flag to enable traffic shifting.
	// +kubebuilder:validation:Optional
	UseTrafficShift *bool `json:"useTrafficShift,omitempty" tf:"use_traffic_shift,omitempty"`
}

type AwsEcsInitParameters struct {

	// (Boolean) Flag to assign a public IP address.
	// Flag to assign a public IP address.
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the ECS cluster to use.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The ARN of the role to use for execution.
	// The ARN of the role to use for execution.
	ExecutionRole *string `json:"executionRole,omitempty" tf:"execution_role,omitempty"`

	// (String) The type of launch configuration to use. Valid options are FARGATE
	// The type of launch configuration to use. Valid options are FARGATE
	LaunchType *string `json:"launchType,omitempty" tf:"launch_type,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsEcsObservation struct {

	// (Boolean) Flag to assign a public IP address.
	// Flag to assign a public IP address.
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the ECS cluster to use.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The ARN of the role to use for execution.
	// The ARN of the role to use for execution.
	ExecutionRole *string `json:"executionRole,omitempty" tf:"execution_role,omitempty"`

	// (String) The type of launch configuration to use. Valid options are FARGATE
	// The type of launch configuration to use. Valid options are FARGATE
	LaunchType *string `json:"launchType,omitempty" tf:"launch_type,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsEcsParameters struct {

	// (Boolean) Flag to assign a public IP address.
	// Flag to assign a public IP address.
	// +kubebuilder:validation:Optional
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the ECS cluster to use.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// (String) The ARN of the role to use for execution.
	// The ARN of the role to use for execution.
	// +kubebuilder:validation:Optional
	ExecutionRole *string `json:"executionRole,omitempty" tf:"execution_role,omitempty"`

	// (String) The type of launch configuration to use. Valid options are FARGATE
	// The type of launch configuration to use. Valid options are FARGATE
	// +kubebuilder:validation:Optional
	LaunchType *string `json:"launchType" tf:"launch_type,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +kubebuilder:validation:Optional
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsLambdaInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The IAM role to use.
	// The IAM role to use.
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsLambdaObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The IAM role to use.
	// The IAM role to use.
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsLambdaParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The IAM role to use.
	// The IAM role to use.
	// +kubebuilder:validation:Optional
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// (Set of String) The security group ids to apply to the ecs service.
	// The security group ids to apply to the ecs service.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Set of String) The subnet ids to apply to the ecs service.
	// The subnet ids to apply to the ecs service.
	// +kubebuilder:validation:Optional
	// +listType=set
	SubnetIds []*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type AwsSSHInitParameters struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the auto scaling group.
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	HostConnectionType *string `json:"hostConnectionType,omitempty" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Block Set) The tags to use when selecting the instances. (see below for nested schema)
	// The tags to use when selecting the instances.
	Tag []TagInitParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Set of String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	// +listType=set
	VPCIds []*string `json:"vpcIds,omitempty" tf:"vpc_ids,omitempty"`
}

type AwsSSHObservation struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the auto scaling group.
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	HostConnectionType *string `json:"hostConnectionType,omitempty" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Block Set) The tags to use when selecting the instances. (see below for nested schema)
	// The tags to use when selecting the instances.
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Set of String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	// +listType=set
	VPCIds []*string `json:"vpcIds,omitempty" tf:"vpc_ids,omitempty"`
}

type AwsSSHParameters struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	// +kubebuilder:validation:Optional
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the auto scaling group.
	// +kubebuilder:validation:Optional
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	// +kubebuilder:validation:Optional
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// +kubebuilder:validation:Optional
	HostConnectionType *string `json:"hostConnectionType" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	// +kubebuilder:validation:Optional
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	// +kubebuilder:validation:Optional
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// (Block Set) The tags to use when selecting the instances. (see below for nested schema)
	// The tags to use when selecting the instances.
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Set of String) The VPC ids to use when selecting the instances.
	// The VPC ids to use when selecting the instances.
	// +kubebuilder:validation:Optional
	// +listType=set
	VPCIds []*string `json:"vpcIds,omitempty" tf:"vpc_ids,omitempty"`
}

type AwsWinrmInitParameters struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the autoscaling group.
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	HostConnectionType *string `json:"hostConnectionType,omitempty" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type AwsWinrmObservation struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	AutoscalingGroupName *string `json:"autoscalingGroupName,omitempty" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the autoscaling group.
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	HostConnectionType *string `json:"hostConnectionType,omitempty" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type AwsWinrmParameters struct {

	// (String) The name of the autoscaling group.
	// The name of the autoscaling group.
	// +kubebuilder:validation:Optional
	AutoscalingGroupName *string `json:"autoscalingGroupName" tf:"autoscaling_group_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (Number) The desired capacity of the auto scaling group.
	// The desired capacity of the autoscaling group.
	// +kubebuilder:validation:Optional
	DesiredCapacity *float64 `json:"desiredCapacity,omitempty" tf:"desired_capacity,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	// +kubebuilder:validation:Optional
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName" tf:"host_connection_attrs_name,omitempty"`

	// (String) The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// The type of host connection to use. Valid options are PRIVATE_DNS, PUBLIC_DNS, PRIVATE_IP, PUBLIC_IP
	// +kubebuilder:validation:Optional
	HostConnectionType *string `json:"hostConnectionType" tf:"host_connection_type,omitempty"`

	// (String) The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('.')[0]}
	// The naming convention to use for the hostname. Defaults to ${host.ec2Instance.privateDnsName.split('\.')[0]}
	// +kubebuilder:validation:Optional
	HostnameConvention *string `json:"hostnameConvention,omitempty" tf:"hostname_convention,omitempty"`

	// (String) The name of the load balancer to use.
	// The name of the load balancer to use.
	// +kubebuilder:validation:Optional
	LoadbalancerName *string `json:"loadbalancerName,omitempty" tf:"loadbalancer_name,omitempty"`

	// (String) The region to deploy to.
	// The region to deploy to.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`
}

type AzureVmssInitParameters struct {

	// (String) The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	// The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Base name.
	// Base name.
	BaseName *string `json:"baseName,omitempty" tf:"base_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of deployment. Valid options are NATIVE_VMSS
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`

	// (String) The username to connect with.
	// The username to connect with.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AzureVmssObservation struct {

	// (String) The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	// The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Base name.
	// Base name.
	BaseName *string `json:"baseName,omitempty" tf:"base_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of deployment. Valid options are NATIVE_VMSS
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`

	// (String) The username to connect with.
	// The username to connect with.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AzureVmssParameters struct {

	// (String) The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	// The type of authentication to use. Valid options are SSH_PUBLIC_KEY.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType" tf:"auth_type,omitempty"`

	// (String) Base name.
	// Base name.
	// +kubebuilder:validation:Optional
	BaseName *string `json:"baseName" tf:"base_name,omitempty"`

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of deployment. Valid options are NATIVE_VMSS
	// +kubebuilder:validation:Optional
	DeploymentType *string `json:"deploymentType" tf:"deployment_type,omitempty"`

	// (String) The name of the host connection attributes to use.
	// The name of the host connection attributes to use.
	// +kubebuilder:validation:Optional
	HostConnectionAttrsName *string `json:"hostConnectionAttrsName,omitempty" tf:"host_connection_attrs_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupName *string `json:"resourceGroupName" tf:"resource_group_name,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	// +kubebuilder:validation:Optional
	SubscriptionID *string `json:"subscriptionId" tf:"subscription_id,omitempty"`

	// (String) The username to connect with.
	// The username to connect with.
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type AzureWebappInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	ResourceGroup *string `json:"resourceGroup,omitempty" tf:"resource_group,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type AzureWebappObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	ResourceGroup *string `json:"resourceGroup,omitempty" tf:"resource_group,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type AzureWebappParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the resource group.
	// The name of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroup *string `json:"resourceGroup" tf:"resource_group,omitempty"`

	// (String) The unique id of the azure subscription.
	// The unique id of the azure subscription.
	// +kubebuilder:validation:Optional
	SubscriptionID *string `json:"subscriptionId" tf:"subscription_id,omitempty"`
}

type CustomInitParameters struct {

	// (String) The template version
	// The template version
	DeploymentTypeTemplateVersion *string `json:"deploymentTypeTemplateVersion,omitempty" tf:"deployment_type_template_version,omitempty"`

	// (Block Set) Variables to be used in the service (see below for nested schema)
	// Variables to be used in the service
	Variable []VariableInitParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type CustomObservation struct {

	// (String) The template version
	// The template version
	DeploymentTypeTemplateVersion *string `json:"deploymentTypeTemplateVersion,omitempty" tf:"deployment_type_template_version,omitempty"`

	// (Block Set) Variables to be used in the service (see below for nested schema)
	// Variables to be used in the service
	Variable []VariableObservation `json:"variable,omitempty" tf:"variable,omitempty"`
}

type CustomParameters struct {

	// (String) The template version
	// The template version
	// +kubebuilder:validation:Optional
	DeploymentTypeTemplateVersion *string `json:"deploymentTypeTemplateVersion" tf:"deployment_type_template_version,omitempty"`

	// (Block Set) Variables to be used in the service (see below for nested schema)
	// Variables to be used in the service
	// +kubebuilder:validation:Optional
	Variable []VariableParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type DatacenterSSHInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the SSH connection attributes to use.
	// The name of the SSH connection attributes to use.
	HostConnectionAttributesName *string `json:"hostConnectionAttributesName,omitempty" tf:"host_connection_attributes_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +listType=set
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`
}

type DatacenterSSHObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the SSH connection attributes to use.
	// The name of the SSH connection attributes to use.
	HostConnectionAttributesName *string `json:"hostConnectionAttributesName,omitempty" tf:"host_connection_attributes_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +listType=set
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`
}

type DatacenterSSHParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the SSH connection attributes to use.
	// The name of the SSH connection attributes to use.
	// +kubebuilder:validation:Optional
	HostConnectionAttributesName *string `json:"hostConnectionAttributesName" tf:"host_connection_attributes_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Hostnames []*string `json:"hostnames" tf:"hostnames,omitempty"`
}

type DatacenterWinrmInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +listType=set
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`

	// (String) The name of the WinRM connection attributes to use.
	// The name of the WinRM connection attributes to use.
	WinrmConnectionAttributesName *string `json:"winrmConnectionAttributesName,omitempty" tf:"winrm_connection_attributes_name,omitempty"`
}

type DatacenterWinrmObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +listType=set
	Hostnames []*string `json:"hostnames,omitempty" tf:"hostnames,omitempty"`

	// (String) The name of the WinRM connection attributes to use.
	// The name of the WinRM connection attributes to use.
	WinrmConnectionAttributesName *string `json:"winrmConnectionAttributesName,omitempty" tf:"winrm_connection_attributes_name,omitempty"`
}

type DatacenterWinrmParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (Set of String) A list of hosts to deploy to.
	// A list of hosts to deploy to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Hostnames []*string `json:"hostnames" tf:"hostnames,omitempty"`

	// (String) The name of the WinRM connection attributes to use.
	// The name of the WinRM connection attributes to use.
	// +kubebuilder:validation:Optional
	WinrmConnectionAttributesName *string `json:"winrmConnectionAttributesName" tf:"winrm_connection_attributes_name,omitempty"`
}

type InfrastructureDefinitionInitParameters struct {

	// (String) The id of the application the infrastructure definition belongs to.
	// The id of the application the infrastructure definition belongs to.
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	AwsAMI []AwsAMIInitParameters `json:"awsAmi,omitempty" tf:"aws_ami,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	AwsEcs []AwsEcsInitParameters `json:"awsEcs,omitempty" tf:"aws_ecs,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws Lambda deployments. (see below for nested schema)
	// The configuration details for Aws Lambda deployments.
	AwsLambda []AwsLambdaInitParameters `json:"awsLambda,omitempty" tf:"aws_lambda,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS SSH deployments. (see below for nested schema)
	// The configuration details for AWS SSH deployments.
	AwsSSH []AwsSSHInitParameters `json:"awsSsh,omitempty" tf:"aws_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS WinRM deployments. (see below for nested schema)
	// The configuration details for AWS WinRM deployments.
	AwsWinrm []AwsWinrmInitParameters `json:"awsWinrm,omitempty" tf:"aws_winrm,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure VMSS deployments. (see below for nested schema)
	// The configuration details for Azure VMSS deployments.
	AzureVmss []AzureVmssInitParameters `json:"azureVmss,omitempty" tf:"azure_vmss,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure WebApp deployments. (see below for nested schema)
	// The configuration details for Azure WebApp deployments.
	AzureWebapp []AzureWebappInitParameters `json:"azureWebapp,omitempty" tf:"azure_webapp,omitempty"`

	// (String) The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	// The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	CloudProviderType *string `json:"cloudProviderType,omitempty" tf:"cloud_provider_type,omitempty"`

	// (Block List, Max: 1) The configuration details for Custom deployments. (see below for nested schema)
	// The configuration details for Custom deployments.
	Custom []CustomInitParameters `json:"custom,omitempty" tf:"custom,omitempty"`

	// (Block List, Max: 1) The configuration details for SSH datacenter deployments. (see below for nested schema)
	// The configuration details for SSH datacenter deployments.
	DatacenterSSH []DatacenterSSHInitParameters `json:"datacenterSsh,omitempty" tf:"datacenter_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for WinRM datacenter deployments. (see below for nested schema)
	// The configuration details for WinRM datacenter deployments.
	DatacenterWinrm []DatacenterWinrmInitParameters `json:"datacenterWinrm,omitempty" tf:"datacenter_winrm,omitempty"`

	// (String) The URI of the deployment template to use. Only used if deployment_type is CUSTOM.
	// The URI of the deployment template to use. Only used if deployment_type is `CUSTOM`.
	DeploymentTemplateURI *string `json:"deploymentTemplateUri,omitempty" tf:"deployment_template_uri,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (String) The id of the environment the infrastructure definition belongs to.
	// The id of the environment the infrastructure definition belongs to.
	EnvID *string `json:"envId,omitempty" tf:"env_id,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes deployments. (see below for nested schema)
	// The configuration details for Kubernetes deployments.
	Kubernetes []KubernetesInitParameters `json:"kubernetes,omitempty" tf:"kubernetes,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes on GCP deployments. (see below for nested schema)
	// The configuration details for Kubernetes on GCP deployments.
	KubernetesGCP []KubernetesGCPInitParameters `json:"kubernetesGcp,omitempty" tf:"kubernetes_gcp,omitempty"`

	// (String) The name of the infrastructure definition
	// The name of the infrastructure definition
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the infrastructure provisioner to use.
	// The name of the infrastructure provisioner to use.
	ProvisionerName *string `json:"provisionerName,omitempty" tf:"provisioner_name,omitempty"`

	// (Set of String) The list of service names to scope this infrastructure definition to.
	// The list of service names to scope this infrastructure definition to.
	// +listType=set
	ScopedServices []*string `json:"scopedServices,omitempty" tf:"scoped_services,omitempty"`

	// (Block List, Max: 1) The configuration details for PCF deployments. (see below for nested schema)
	// The configuration details for PCF deployments.
	Tanzu []TanzuInitParameters `json:"tanzu,omitempty" tf:"tanzu,omitempty"`
}

type InfrastructureDefinitionObservation struct {

	// (String) The id of the application the infrastructure definition belongs to.
	// The id of the application the infrastructure definition belongs to.
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	AwsAMI []AwsAMIObservation `json:"awsAmi,omitempty" tf:"aws_ami,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	AwsEcs []AwsEcsObservation `json:"awsEcs,omitempty" tf:"aws_ecs,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws Lambda deployments. (see below for nested schema)
	// The configuration details for Aws Lambda deployments.
	AwsLambda []AwsLambdaObservation `json:"awsLambda,omitempty" tf:"aws_lambda,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS SSH deployments. (see below for nested schema)
	// The configuration details for AWS SSH deployments.
	AwsSSH []AwsSSHObservation `json:"awsSsh,omitempty" tf:"aws_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS WinRM deployments. (see below for nested schema)
	// The configuration details for AWS WinRM deployments.
	AwsWinrm []AwsWinrmObservation `json:"awsWinrm,omitempty" tf:"aws_winrm,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure VMSS deployments. (see below for nested schema)
	// The configuration details for Azure VMSS deployments.
	AzureVmss []AzureVmssObservation `json:"azureVmss,omitempty" tf:"azure_vmss,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure WebApp deployments. (see below for nested schema)
	// The configuration details for Azure WebApp deployments.
	AzureWebapp []AzureWebappObservation `json:"azureWebapp,omitempty" tf:"azure_webapp,omitempty"`

	// (String) The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	// The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	CloudProviderType *string `json:"cloudProviderType,omitempty" tf:"cloud_provider_type,omitempty"`

	// (Block List, Max: 1) The configuration details for Custom deployments. (see below for nested schema)
	// The configuration details for Custom deployments.
	Custom []CustomObservation `json:"custom,omitempty" tf:"custom,omitempty"`

	// (Block List, Max: 1) The configuration details for SSH datacenter deployments. (see below for nested schema)
	// The configuration details for SSH datacenter deployments.
	DatacenterSSH []DatacenterSSHObservation `json:"datacenterSsh,omitempty" tf:"datacenter_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for WinRM datacenter deployments. (see below for nested schema)
	// The configuration details for WinRM datacenter deployments.
	DatacenterWinrm []DatacenterWinrmObservation `json:"datacenterWinrm,omitempty" tf:"datacenter_winrm,omitempty"`

	// (String) The URI of the deployment template to use. Only used if deployment_type is CUSTOM.
	// The URI of the deployment template to use. Only used if deployment_type is `CUSTOM`.
	DeploymentTemplateURI *string `json:"deploymentTemplateUri,omitempty" tf:"deployment_template_uri,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (String) The id of the environment the infrastructure definition belongs to.
	// The id of the environment the infrastructure definition belongs to.
	EnvID *string `json:"envId,omitempty" tf:"env_id,omitempty"`

	// (String) The unique id of the infrastructure definition.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes deployments. (see below for nested schema)
	// The configuration details for Kubernetes deployments.
	Kubernetes []KubernetesObservation `json:"kubernetes,omitempty" tf:"kubernetes,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes on GCP deployments. (see below for nested schema)
	// The configuration details for Kubernetes on GCP deployments.
	KubernetesGCP []KubernetesGCPObservation `json:"kubernetesGcp,omitempty" tf:"kubernetes_gcp,omitempty"`

	// (String) The name of the infrastructure definition
	// The name of the infrastructure definition
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the infrastructure provisioner to use.
	// The name of the infrastructure provisioner to use.
	ProvisionerName *string `json:"provisionerName,omitempty" tf:"provisioner_name,omitempty"`

	// (Set of String) The list of service names to scope this infrastructure definition to.
	// The list of service names to scope this infrastructure definition to.
	// +listType=set
	ScopedServices []*string `json:"scopedServices,omitempty" tf:"scoped_services,omitempty"`

	// (Block List, Max: 1) The configuration details for PCF deployments. (see below for nested schema)
	// The configuration details for PCF deployments.
	Tanzu []TanzuObservation `json:"tanzu,omitempty" tf:"tanzu,omitempty"`
}

type InfrastructureDefinitionParameters struct {

	// (String) The id of the application the infrastructure definition belongs to.
	// The id of the application the infrastructure definition belongs to.
	// +kubebuilder:validation:Optional
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	// +kubebuilder:validation:Optional
	AwsAMI []AwsAMIParameters `json:"awsAmi,omitempty" tf:"aws_ami,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws AMI deployments. (see below for nested schema)
	// The configuration details for Aws AMI deployments.
	// +kubebuilder:validation:Optional
	AwsEcs []AwsEcsParameters `json:"awsEcs,omitempty" tf:"aws_ecs,omitempty"`

	// (Block List, Max: 1) The configuration details for Aws Lambda deployments. (see below for nested schema)
	// The configuration details for Aws Lambda deployments.
	// +kubebuilder:validation:Optional
	AwsLambda []AwsLambdaParameters `json:"awsLambda,omitempty" tf:"aws_lambda,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS SSH deployments. (see below for nested schema)
	// The configuration details for AWS SSH deployments.
	// +kubebuilder:validation:Optional
	AwsSSH []AwsSSHParameters `json:"awsSsh,omitempty" tf:"aws_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for AWS WinRM deployments. (see below for nested schema)
	// The configuration details for AWS WinRM deployments.
	// +kubebuilder:validation:Optional
	AwsWinrm []AwsWinrmParameters `json:"awsWinrm,omitempty" tf:"aws_winrm,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure VMSS deployments. (see below for nested schema)
	// The configuration details for Azure VMSS deployments.
	// +kubebuilder:validation:Optional
	AzureVmss []AzureVmssParameters `json:"azureVmss,omitempty" tf:"azure_vmss,omitempty"`

	// (Block List, Max: 1) The configuration details for Azure WebApp deployments. (see below for nested schema)
	// The configuration details for Azure WebApp deployments.
	// +kubebuilder:validation:Optional
	AzureWebapp []AzureWebappParameters `json:"azureWebapp,omitempty" tf:"azure_webapp,omitempty"`

	// (String) The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	// The type of the cloud provider to connect with. Valid options are AWS, AZURE, CUSTOM, PHYSICAL_DATA_CENTER, KUBERNETES_CLUSTER, PCF, SPOT_INST
	// +kubebuilder:validation:Optional
	CloudProviderType *string `json:"cloudProviderType,omitempty" tf:"cloud_provider_type,omitempty"`

	// (Block List, Max: 1) The configuration details for Custom deployments. (see below for nested schema)
	// The configuration details for Custom deployments.
	// +kubebuilder:validation:Optional
	Custom []CustomParameters `json:"custom,omitempty" tf:"custom,omitempty"`

	// (Block List, Max: 1) The configuration details for SSH datacenter deployments. (see below for nested schema)
	// The configuration details for SSH datacenter deployments.
	// +kubebuilder:validation:Optional
	DatacenterSSH []DatacenterSSHParameters `json:"datacenterSsh,omitempty" tf:"datacenter_ssh,omitempty"`

	// (Block List, Max: 1) The configuration details for WinRM datacenter deployments. (see below for nested schema)
	// The configuration details for WinRM datacenter deployments.
	// +kubebuilder:validation:Optional
	DatacenterWinrm []DatacenterWinrmParameters `json:"datacenterWinrm,omitempty" tf:"datacenter_winrm,omitempty"`

	// (String) The URI of the deployment template to use. Only used if deployment_type is CUSTOM.
	// The URI of the deployment template to use. Only used if deployment_type is `CUSTOM`.
	// +kubebuilder:validation:Optional
	DeploymentTemplateURI *string `json:"deploymentTemplateUri,omitempty" tf:"deployment_template_uri,omitempty"`

	// (String) The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// The type of the deployment to use. Valid options are AMI, AWS_CODEDEPLOY, AWS_LAMBDA, AZURE_VMSS, AZURE_WEBAPP, CUSTOM, ECS, HELM, KUBERNETES, PCF, SSH, WINRM
	// +kubebuilder:validation:Optional
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (String) The id of the environment the infrastructure definition belongs to.
	// The id of the environment the infrastructure definition belongs to.
	// +kubebuilder:validation:Optional
	EnvID *string `json:"envId,omitempty" tf:"env_id,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes deployments. (see below for nested schema)
	// The configuration details for Kubernetes deployments.
	// +kubebuilder:validation:Optional
	Kubernetes []KubernetesParameters `json:"kubernetes,omitempty" tf:"kubernetes,omitempty"`

	// (Block List, Max: 1) The configuration details for Kubernetes on GCP deployments. (see below for nested schema)
	// The configuration details for Kubernetes on GCP deployments.
	// +kubebuilder:validation:Optional
	KubernetesGCP []KubernetesGCPParameters `json:"kubernetesGcp,omitempty" tf:"kubernetes_gcp,omitempty"`

	// (String) The name of the infrastructure definition
	// The name of the infrastructure definition
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the infrastructure provisioner to use.
	// The name of the infrastructure provisioner to use.
	// +kubebuilder:validation:Optional
	ProvisionerName *string `json:"provisionerName,omitempty" tf:"provisioner_name,omitempty"`

	// (Set of String) The list of service names to scope this infrastructure definition to.
	// The list of service names to scope this infrastructure definition to.
	// +kubebuilder:validation:Optional
	// +listType=set
	ScopedServices []*string `json:"scopedServices,omitempty" tf:"scoped_services,omitempty"`

	// (Block List, Max: 1) The configuration details for PCF deployments. (see below for nested schema)
	// The configuration details for PCF deployments.
	// +kubebuilder:validation:Optional
	Tanzu []TanzuParameters `json:"tanzu,omitempty" tf:"tanzu,omitempty"`
}

type KubernetesGCPInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the cluster being deployed to.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release.
	ReleaseName *string `json:"releaseName,omitempty" tf:"release_name,omitempty"`
}

type KubernetesGCPObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the cluster being deployed to.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release.
	ReleaseName *string `json:"releaseName,omitempty" tf:"release_name,omitempty"`
}

type KubernetesGCPParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The name of the ECS cluster to use.
	// The name of the cluster being deployed to.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release.
	// +kubebuilder:validation:Optional
	ReleaseName *string `json:"releaseName" tf:"release_name,omitempty"`
}

type KubernetesInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release. When using Helm Native the default is ${infra.kubernetes.infraId}. For standard Kubernetes manifests the default is release-${infra.kubernetes.infraId}
	ReleaseName *string `json:"releaseName,omitempty" tf:"release_name,omitempty"`
}

type KubernetesObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release. When using Helm Native the default is ${infra.kubernetes.infraId}. For standard Kubernetes manifests the default is release-${infra.kubernetes.infraId}
	ReleaseName *string `json:"releaseName,omitempty" tf:"release_name,omitempty"`
}

type KubernetesParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The namespace in Kubernetes to deploy to.
	// The namespace in Kubernetes to deploy to.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace" tf:"namespace,omitempty"`

	// ${infra.kubernetes.infraId}
	// The naming convention of the release. When using Helm Native the default is ${infra.kubernetes.infraId}. For standard Kubernetes manifests the default is release-${infra.kubernetes.infraId}
	// +kubebuilder:validation:Optional
	ReleaseName *string `json:"releaseName" tf:"release_name,omitempty"`
}

type TagInitParameters struct {

	// (String) The key of the tag.
	// The key of the tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) The value of the tag.
	// The value of the tag.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TagObservation struct {

	// (String) The key of the tag.
	// The key of the tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) The value of the tag.
	// The value of the tag.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TagParameters struct {

	// (String) The key of the tag.
	// The key of the tag.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String) The value of the tag.
	// The value of the tag.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type TanzuInitParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The PCF organization to use.
	// The PCF organization to use.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The PCF space to deploy to.
	// The PCF space to deploy to.
	Space *string `json:"space,omitempty" tf:"space,omitempty"`
}

type TanzuObservation struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	CloudProviderName *string `json:"cloudProviderName,omitempty" tf:"cloud_provider_name,omitempty"`

	// (String) The PCF organization to use.
	// The PCF organization to use.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The PCF space to deploy to.
	// The PCF space to deploy to.
	Space *string `json:"space,omitempty" tf:"space,omitempty"`
}

type TanzuParameters struct {

	// (String) The name of the cloud provider to connect with.
	// The name of the cloud provider to connect with.
	// +kubebuilder:validation:Optional
	CloudProviderName *string `json:"cloudProviderName" tf:"cloud_provider_name,omitempty"`

	// (String) The PCF organization to use.
	// The PCF organization to use.
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization" tf:"organization,omitempty"`

	// (String) The PCF space to deploy to.
	// The PCF space to deploy to.
	// +kubebuilder:validation:Optional
	Space *string `json:"space" tf:"space,omitempty"`
}

type VariableInitParameters struct {

	// (String) The name of the infrastructure definition
	// Name of the variable
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The value of the tag.
	// Value of the variable
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type VariableObservation struct {

	// (String) The name of the infrastructure definition
	// Name of the variable
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The value of the tag.
	// Value of the variable
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type VariableParameters struct {

	// (String) The name of the infrastructure definition
	// Name of the variable
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The value of the tag.
	// Value of the variable
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// InfrastructureDefinitionSpec defines the desired state of InfrastructureDefinition
type InfrastructureDefinitionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InfrastructureDefinitionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InfrastructureDefinitionInitParameters `json:"initProvider,omitempty"`
}

// InfrastructureDefinitionStatus defines the observed state of InfrastructureDefinition.
type InfrastructureDefinitionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InfrastructureDefinitionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InfrastructureDefinition is the Schema for the InfrastructureDefinitions API. Resource for creating am infrastructure definition. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type InfrastructureDefinition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.appId) || (has(self.initProvider) && has(self.initProvider.appId))",message="spec.forProvider.appId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProviderType) || (has(self.initProvider) && has(self.initProvider.cloudProviderType))",message="spec.forProvider.cloudProviderType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deploymentType) || (has(self.initProvider) && has(self.initProvider.deploymentType))",message="spec.forProvider.deploymentType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.envId) || (has(self.initProvider) && has(self.initProvider.envId))",message="spec.forProvider.envId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   InfrastructureDefinitionSpec   `json:"spec"`
	Status InfrastructureDefinitionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InfrastructureDefinitionList contains a list of InfrastructureDefinitions
type InfrastructureDefinitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InfrastructureDefinition `json:"items"`
}

// Repository type metadata.
var (
	InfrastructureDefinition_Kind             = "InfrastructureDefinition"
	InfrastructureDefinition_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InfrastructureDefinition_Kind}.String()
	InfrastructureDefinition_KindAPIVersion   = InfrastructureDefinition_Kind + "." + CRDGroupVersion.String()
	InfrastructureDefinition_GroupVersionKind = CRDGroupVersion.WithKind(InfrastructureDefinition_Kind)
)

func init() {
	SchemeBuilder.Register(&InfrastructureDefinition{}, &InfrastructureDefinitionList{})
}
