// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GitxWebhookInitParameters struct {

	// (String) ConnectorRef to be used to create Gitx webhook.
	// ConnectorRef to be used to create Gitx webhook.
	ConnectorRef *string `json:"connectorRef,omitempty" tf:"connector_ref,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) Folder Paths
	// Folder Paths
	FolderPaths []*string `json:"folderPaths,omitempty" tf:"folder_paths,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Flag to enable the webhook
	// Flag to enable the webhook
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Repo Identifier for Gitx webhook.
	// Repo Identifier for Gitx webhook.
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GitxWebhookObservation struct {

	// (String) ConnectorRef to be used to create Gitx webhook.
	// ConnectorRef to be used to create Gitx webhook.
	ConnectorRef *string `json:"connectorRef,omitempty" tf:"connector_ref,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) Folder Paths
	// Folder Paths
	FolderPaths []*string `json:"folderPaths,omitempty" tf:"folder_paths,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Flag to enable the webhook
	// Flag to enable the webhook
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Repo Identifier for Gitx webhook.
	// Repo Identifier for Gitx webhook.
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GitxWebhookParameters struct {

	// (String) ConnectorRef to be used to create Gitx webhook.
	// ConnectorRef to be used to create Gitx webhook.
	// +kubebuilder:validation:Optional
	ConnectorRef *string `json:"connectorRef,omitempty" tf:"connector_ref,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) Folder Paths
	// Folder Paths
	// +kubebuilder:validation:Optional
	FolderPaths []*string `json:"folderPaths,omitempty" tf:"folder_paths,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Flag to enable the webhook
	// Flag to enable the webhook
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Repo Identifier for Gitx webhook.
	// Repo Identifier for Gitx webhook.
	// +kubebuilder:validation:Optional
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// GitxWebhookSpec defines the desired state of GitxWebhook
type GitxWebhookSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GitxWebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GitxWebhookInitParameters `json:"initProvider,omitempty"`
}

// GitxWebhookStatus defines the observed state of GitxWebhook.
type GitxWebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GitxWebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GitxWebhook is the Schema for the GitxWebhooks API. Resource for creating a Harness GitX Webhook.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type GitxWebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.connectorRef) || (has(self.initProvider) && has(self.initProvider.connectorRef))",message="spec.forProvider.connectorRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repoName) || (has(self.initProvider) && has(self.initProvider.repoName))",message="spec.forProvider.repoName is a required parameter"
	Spec   GitxWebhookSpec   `json:"spec"`
	Status GitxWebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GitxWebhookList contains a list of GitxWebhooks
type GitxWebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GitxWebhook `json:"items"`
}

// Repository type metadata.
var (
	GitxWebhook_Kind             = "GitxWebhook"
	GitxWebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GitxWebhook_Kind}.String()
	GitxWebhook_KindAPIVersion   = GitxWebhook_Kind + "." + CRDGroupVersion.String()
	GitxWebhook_GroupVersionKind = CRDGroupVersion.WithKind(GitxWebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&GitxWebhook{}, &GitxWebhookList{})
}
