//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorInitParameters) DeepCopyInto(out *ConnectorInitParameters) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorInitParameters.
func (in *ConnectorInitParameters) DeepCopy() *ConnectorInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorObservation) DeepCopyInto(out *ConnectorObservation) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorObservation.
func (in *ConnectorObservation) DeepCopy() *ConnectorObservation {
	if in == nil {
		return nil
	}
	out := new(ConnectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorParameters) DeepCopyInto(out *ConnectorParameters) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorParameters.
func (in *ConnectorParameters) DeepCopy() *ConnectorParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariableInitParameters) DeepCopyInto(out *EnvironmentVariableInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariableInitParameters.
func (in *EnvironmentVariableInitParameters) DeepCopy() *EnvironmentVariableInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariableInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariableObservation) DeepCopyInto(out *EnvironmentVariableObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariableObservation.
func (in *EnvironmentVariableObservation) DeepCopy() *EnvironmentVariableObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariableParameters) DeepCopyInto(out *EnvironmentVariableParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariableParameters.
func (in *EnvironmentVariableParameters) DeepCopy() *EnvironmentVariableParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Module) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleInitParameters) DeepCopyInto(out *ModuleInitParameters) {
	*out = *in
	if in.ConnectorOrg != nil {
		in, out := &in.ConnectorOrg, &out.ConnectorOrg
		*out = new(string)
		**out = **in
	}
	if in.ConnectorProject != nil {
		in, out := &in.ConnectorProject, &out.ConnectorProject
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GitTagStyle != nil {
		in, out := &in.GitTagStyle, &out.GitTagStyle
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipeline != nil {
		in, out := &in.OnboardingPipeline, &out.OnboardingPipeline
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineOrg != nil {
		in, out := &in.OnboardingPipelineOrg, &out.OnboardingPipelineOrg
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineProject != nil {
		in, out := &in.OnboardingPipelineProject, &out.OnboardingPipelineProject
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineSync != nil {
		in, out := &in.OnboardingPipelineSync, &out.OnboardingPipelineSync
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURL != nil {
		in, out := &in.RepositoryURL, &out.RepositoryURL
		*out = new(string)
		**out = **in
	}
	if in.StorageType != nil {
		in, out := &in.StorageType, &out.StorageType
		*out = new(string)
		**out = **in
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(float64)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(string)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleInitParameters.
func (in *ModuleInitParameters) DeepCopy() *ModuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleList) DeepCopyInto(out *ModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleList.
func (in *ModuleList) DeepCopy() *ModuleList {
	if in == nil {
		return nil
	}
	out := new(ModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleObservation) DeepCopyInto(out *ModuleObservation) {
	*out = *in
	if in.ConnectorOrg != nil {
		in, out := &in.ConnectorOrg, &out.ConnectorOrg
		*out = new(string)
		**out = **in
	}
	if in.ConnectorProject != nil {
		in, out := &in.ConnectorProject, &out.ConnectorProject
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GitTagStyle != nil {
		in, out := &in.GitTagStyle, &out.GitTagStyle
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipeline != nil {
		in, out := &in.OnboardingPipeline, &out.OnboardingPipeline
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineOrg != nil {
		in, out := &in.OnboardingPipelineOrg, &out.OnboardingPipelineOrg
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineProject != nil {
		in, out := &in.OnboardingPipelineProject, &out.OnboardingPipelineProject
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineSync != nil {
		in, out := &in.OnboardingPipelineSync, &out.OnboardingPipelineSync
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURL != nil {
		in, out := &in.RepositoryURL, &out.RepositoryURL
		*out = new(string)
		**out = **in
	}
	if in.StorageType != nil {
		in, out := &in.StorageType, &out.StorageType
		*out = new(string)
		**out = **in
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(float64)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(string)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleObservation.
func (in *ModuleObservation) DeepCopy() *ModuleObservation {
	if in == nil {
		return nil
	}
	out := new(ModuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleParameters) DeepCopyInto(out *ModuleParameters) {
	*out = *in
	if in.ConnectorOrg != nil {
		in, out := &in.ConnectorOrg, &out.ConnectorOrg
		*out = new(string)
		**out = **in
	}
	if in.ConnectorProject != nil {
		in, out := &in.ConnectorProject, &out.ConnectorProject
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GitTagStyle != nil {
		in, out := &in.GitTagStyle, &out.GitTagStyle
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipeline != nil {
		in, out := &in.OnboardingPipeline, &out.OnboardingPipeline
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineOrg != nil {
		in, out := &in.OnboardingPipelineOrg, &out.OnboardingPipelineOrg
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineProject != nil {
		in, out := &in.OnboardingPipelineProject, &out.OnboardingPipelineProject
		*out = new(string)
		**out = **in
	}
	if in.OnboardingPipelineSync != nil {
		in, out := &in.OnboardingPipelineSync, &out.OnboardingPipelineSync
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURL != nil {
		in, out := &in.RepositoryURL, &out.RepositoryURL
		*out = new(string)
		**out = **in
	}
	if in.StorageType != nil {
		in, out := &in.StorageType, &out.StorageType
		*out = new(string)
		**out = **in
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(float64)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(string)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleParameters.
func (in *ModuleParameters) DeepCopy() *ModuleParameters {
	if in == nil {
		return nil
	}
	out := new(ModuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpec) DeepCopyInto(out *ModuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpec.
func (in *ModuleSpec) DeepCopy() *ModuleSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTesting) DeepCopyInto(out *ModuleTesting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTesting.
func (in *ModuleTesting) DeepCopy() *ModuleTesting {
	if in == nil {
		return nil
	}
	out := new(ModuleTesting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleTesting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingInitParameters) DeepCopyInto(out *ModuleTestingInitParameters) {
	*out = *in
	if in.ModuleID != nil {
		in, out := &in.ModuleID, &out.ModuleID
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
	if in.TestingEnabled != nil {
		in, out := &in.TestingEnabled, &out.TestingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TestingMetadata != nil {
		in, out := &in.TestingMetadata, &out.TestingMetadata
		*out = make([]TestingMetadataInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Updated != nil {
		in, out := &in.Updated, &out.Updated
		*out = new(float64)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingInitParameters.
func (in *ModuleTestingInitParameters) DeepCopy() *ModuleTestingInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingList) DeepCopyInto(out *ModuleTestingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleTesting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingList.
func (in *ModuleTestingList) DeepCopy() *ModuleTestingList {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleTestingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingObservation) DeepCopyInto(out *ModuleTestingObservation) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GitTagStyle != nil {
		in, out := &in.GitTagStyle, &out.GitTagStyle
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ModuleError != nil {
		in, out := &in.ModuleError, &out.ModuleError
		*out = new(string)
		**out = **in
	}
	if in.ModuleID != nil {
		in, out := &in.ModuleID, &out.ModuleID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURL != nil {
		in, out := &in.RepositoryURL, &out.RepositoryURL
		*out = new(string)
		**out = **in
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(float64)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(string)
		**out = **in
	}
	if in.TestingEnabled != nil {
		in, out := &in.TestingEnabled, &out.TestingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TestingMetadata != nil {
		in, out := &in.TestingMetadata, &out.TestingMetadata
		*out = make([]TestingMetadataObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Updated != nil {
		in, out := &in.Updated, &out.Updated
		*out = new(float64)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingObservation.
func (in *ModuleTestingObservation) DeepCopy() *ModuleTestingObservation {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingParameters) DeepCopyInto(out *ModuleTestingParameters) {
	*out = *in
	if in.ModuleID != nil {
		in, out := &in.ModuleID, &out.ModuleID
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
	if in.TestingEnabled != nil {
		in, out := &in.TestingEnabled, &out.TestingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TestingMetadata != nil {
		in, out := &in.TestingMetadata, &out.TestingMetadata
		*out = make([]TestingMetadataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Updated != nil {
		in, out := &in.Updated, &out.Updated
		*out = new(float64)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingParameters.
func (in *ModuleTestingParameters) DeepCopy() *ModuleTestingParameters {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingSpec) DeepCopyInto(out *ModuleTestingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingSpec.
func (in *ModuleTestingSpec) DeepCopy() *ModuleTestingSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleTestingStatus) DeepCopyInto(out *ModuleTestingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleTestingStatus.
func (in *ModuleTestingStatus) DeepCopy() *ModuleTestingStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleTestingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInitParameters) DeepCopyInto(out *ProviderInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInitParameters.
func (in *ProviderInitParameters) DeepCopy() *ProviderInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderObservation) DeepCopyInto(out *ProviderObservation) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Updated != nil {
		in, out := &in.Updated, &out.Updated
		*out = new(float64)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]VersionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderObservation.
func (in *ProviderObservation) DeepCopy() *ProviderObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderParameters) DeepCopyInto(out *ProviderParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderParameters.
func (in *ProviderParameters) DeepCopy() *ProviderParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKey) DeepCopyInto(out *ProviderSigningKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKey.
func (in *ProviderSigningKey) DeepCopy() *ProviderSigningKey {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderSigningKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeyInitParameters) DeepCopyInto(out *ProviderSigningKeyInitParameters) {
	*out = *in
	in.ASCIIArmorSecretRef.DeepCopyInto(&out.ASCIIArmorSecretRef)
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeyInitParameters.
func (in *ProviderSigningKeyInitParameters) DeepCopy() *ProviderSigningKeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeyList) DeepCopyInto(out *ProviderSigningKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderSigningKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeyList.
func (in *ProviderSigningKeyList) DeepCopy() *ProviderSigningKeyList {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderSigningKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeyObservation) DeepCopyInto(out *ProviderSigningKeyObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeyObservation.
func (in *ProviderSigningKeyObservation) DeepCopy() *ProviderSigningKeyObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeyParameters) DeepCopyInto(out *ProviderSigningKeyParameters) {
	*out = *in
	in.ASCIIArmorSecretRef.DeepCopyInto(&out.ASCIIArmorSecretRef)
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeyParameters.
func (in *ProviderSigningKeyParameters) DeepCopy() *ProviderSigningKeyParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeySpec) DeepCopyInto(out *ProviderSigningKeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeySpec.
func (in *ProviderSigningKeySpec) DeepCopy() *ProviderSigningKeySpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSigningKeyStatus) DeepCopyInto(out *ProviderSigningKeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSigningKeyStatus.
func (in *ProviderSigningKeyStatus) DeepCopy() *ProviderSigningKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderSigningKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersion) DeepCopyInto(out *ProviderVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersion.
func (in *ProviderVersion) DeepCopy() *ProviderVersion {
	if in == nil {
		return nil
	}
	out := new(ProviderVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFile) DeepCopyInto(out *ProviderVersionFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFile.
func (in *ProviderVersionFile) DeepCopy() *ProviderVersionFile {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersionFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileInitParameters) DeepCopyInto(out *ProviderVersionFileInitParameters) {
	*out = *in
	if in.FilePath != nil {
		in, out := &in.FilePath, &out.FilePath
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileInitParameters.
func (in *ProviderVersionFileInitParameters) DeepCopy() *ProviderVersionFileInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileList) DeepCopyInto(out *ProviderVersionFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderVersionFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileList.
func (in *ProviderVersionFileList) DeepCopy() *ProviderVersionFileList {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersionFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileObservation) DeepCopyInto(out *ProviderVersionFileObservation) {
	*out = *in
	if in.FilePath != nil {
		in, out := &in.FilePath, &out.FilePath
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileObservation.
func (in *ProviderVersionFileObservation) DeepCopy() *ProviderVersionFileObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileParameters) DeepCopyInto(out *ProviderVersionFileParameters) {
	*out = *in
	if in.FilePath != nil {
		in, out := &in.FilePath, &out.FilePath
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileParameters.
func (in *ProviderVersionFileParameters) DeepCopy() *ProviderVersionFileParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileSpec) DeepCopyInto(out *ProviderVersionFileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileSpec.
func (in *ProviderVersionFileSpec) DeepCopy() *ProviderVersionFileSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionFileStatus) DeepCopyInto(out *ProviderVersionFileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionFileStatus.
func (in *ProviderVersionFileStatus) DeepCopy() *ProviderVersionFileStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionInitParameters) DeepCopyInto(out *ProviderVersionInitParameters) {
	*out = *in
	if in.GpgKeyID != nil {
		in, out := &in.GpgKeyID, &out.GpgKeyID
		*out = new(string)
		**out = **in
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionInitParameters.
func (in *ProviderVersionInitParameters) DeepCopy() *ProviderVersionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionList) DeepCopyInto(out *ProviderVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionList.
func (in *ProviderVersionList) DeepCopy() *ProviderVersionList {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionObservation) DeepCopyInto(out *ProviderVersionObservation) {
	*out = *in
	if in.GpgKeyID != nil {
		in, out := &in.GpgKeyID, &out.GpgKeyID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionObservation.
func (in *ProviderVersionObservation) DeepCopy() *ProviderVersionObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionParameters) DeepCopyInto(out *ProviderVersionParameters) {
	*out = *in
	if in.GpgKeyID != nil {
		in, out := &in.GpgKeyID, &out.GpgKeyID
		*out = new(string)
		**out = **in
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionParameters.
func (in *ProviderVersionParameters) DeepCopy() *ProviderVersionParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublish) DeepCopyInto(out *ProviderVersionPublish) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublish.
func (in *ProviderVersionPublish) DeepCopy() *ProviderVersionPublish {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersionPublish) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishInitParameters) DeepCopyInto(out *ProviderVersionPublishInitParameters) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishInitParameters.
func (in *ProviderVersionPublishInitParameters) DeepCopy() *ProviderVersionPublishInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishList) DeepCopyInto(out *ProviderVersionPublishList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderVersionPublish, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishList.
func (in *ProviderVersionPublishList) DeepCopy() *ProviderVersionPublishList {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderVersionPublishList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishObservation) DeepCopyInto(out *ProviderVersionPublishObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Published != nil {
		in, out := &in.Published, &out.Published
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishObservation.
func (in *ProviderVersionPublishObservation) DeepCopy() *ProviderVersionPublishObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishParameters) DeepCopyInto(out *ProviderVersionPublishParameters) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishParameters.
func (in *ProviderVersionPublishParameters) DeepCopy() *ProviderVersionPublishParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishSpec) DeepCopyInto(out *ProviderVersionPublishSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishSpec.
func (in *ProviderVersionPublishSpec) DeepCopy() *ProviderVersionPublishSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionPublishStatus) DeepCopyInto(out *ProviderVersionPublishStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionPublishStatus.
func (in *ProviderVersionPublishStatus) DeepCopy() *ProviderVersionPublishStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionPublishStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionSpec) DeepCopyInto(out *ProviderVersionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionSpec.
func (in *ProviderVersionSpec) DeepCopy() *ProviderVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersionStatus) DeepCopyInto(out *ProviderVersionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersionStatus.
func (in *ProviderVersionStatus) DeepCopy() *ProviderVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableFileInitParameters) DeepCopyInto(out *TerraformVariableFileInitParameters) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositorySha != nil {
		in, out := &in.RepositorySha, &out.RepositorySha
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableFileInitParameters.
func (in *TerraformVariableFileInitParameters) DeepCopy() *TerraformVariableFileInitParameters {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableFileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableFileObservation) DeepCopyInto(out *TerraformVariableFileObservation) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositorySha != nil {
		in, out := &in.RepositorySha, &out.RepositorySha
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableFileObservation.
func (in *TerraformVariableFileObservation) DeepCopy() *TerraformVariableFileObservation {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableFileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableFileParameters) DeepCopyInto(out *TerraformVariableFileParameters) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryBranch != nil {
		in, out := &in.RepositoryBranch, &out.RepositoryBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryCommit != nil {
		in, out := &in.RepositoryCommit, &out.RepositoryCommit
		*out = new(string)
		**out = **in
	}
	if in.RepositoryConnector != nil {
		in, out := &in.RepositoryConnector, &out.RepositoryConnector
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.RepositorySha != nil {
		in, out := &in.RepositorySha, &out.RepositorySha
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableFileParameters.
func (in *TerraformVariableFileParameters) DeepCopy() *TerraformVariableFileParameters {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableFileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableInitParameters) DeepCopyInto(out *TerraformVariableInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableInitParameters.
func (in *TerraformVariableInitParameters) DeepCopy() *TerraformVariableInitParameters {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableObservation) DeepCopyInto(out *TerraformVariableObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableObservation.
func (in *TerraformVariableObservation) DeepCopy() *TerraformVariableObservation {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerraformVariableParameters) DeepCopyInto(out *TerraformVariableParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerraformVariableParameters.
func (in *TerraformVariableParameters) DeepCopy() *TerraformVariableParameters {
	if in == nil {
		return nil
	}
	out := new(TerraformVariableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestingMetadataInitParameters) DeepCopyInto(out *TestingMetadataInitParameters) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestingMetadataInitParameters.
func (in *TestingMetadataInitParameters) DeepCopy() *TestingMetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(TestingMetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestingMetadataObservation) DeepCopyInto(out *TestingMetadataObservation) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestingMetadataObservation.
func (in *TestingMetadataObservation) DeepCopy() *TestingMetadataObservation {
	if in == nil {
		return nil
	}
	out := new(TestingMetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestingMetadataParameters) DeepCopyInto(out *TestingMetadataParameters) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProviderConnector != nil {
		in, out := &in.ProviderConnector, &out.ProviderConnector
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerType != nil {
		in, out := &in.ProvisionerType, &out.ProvisionerType
		*out = new(string)
		**out = **in
	}
	if in.ProvisionerVersion != nil {
		in, out := &in.ProvisionerVersion, &out.ProvisionerVersion
		*out = new(string)
		**out = **in
	}
	if in.ReleasePipeline != nil {
		in, out := &in.ReleasePipeline, &out.ReleasePipeline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestingMetadataParameters.
func (in *TestingMetadataParameters) DeepCopy() *TestingMetadataParameters {
	if in == nil {
		return nil
	}
	out := new(TestingMetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSet) DeepCopyInto(out *VariableSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSet.
func (in *VariableSet) DeepCopy() *VariableSet {
	if in == nil {
		return nil
	}
	out := new(VariableSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VariableSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetInitParameters) DeepCopyInto(out *VariableSetInitParameters) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = make([]ConnectorInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariable != nil {
		in, out := &in.EnvironmentVariable, &out.EnvironmentVariable
		*out = make([]EnvironmentVariableInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerraformVariable != nil {
		in, out := &in.TerraformVariable, &out.TerraformVariable
		*out = make([]TerraformVariableInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerraformVariableFile != nil {
		in, out := &in.TerraformVariableFile, &out.TerraformVariableFile
		*out = make([]TerraformVariableFileInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetInitParameters.
func (in *VariableSetInitParameters) DeepCopy() *VariableSetInitParameters {
	if in == nil {
		return nil
	}
	out := new(VariableSetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetList) DeepCopyInto(out *VariableSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VariableSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetList.
func (in *VariableSetList) DeepCopy() *VariableSetList {
	if in == nil {
		return nil
	}
	out := new(VariableSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VariableSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetObservation) DeepCopyInto(out *VariableSetObservation) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = make([]ConnectorObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariable != nil {
		in, out := &in.EnvironmentVariable, &out.EnvironmentVariable
		*out = make([]EnvironmentVariableObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerraformVariable != nil {
		in, out := &in.TerraformVariable, &out.TerraformVariable
		*out = make([]TerraformVariableObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerraformVariableFile != nil {
		in, out := &in.TerraformVariableFile, &out.TerraformVariableFile
		*out = make([]TerraformVariableFileObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetObservation.
func (in *VariableSetObservation) DeepCopy() *VariableSetObservation {
	if in == nil {
		return nil
	}
	out := new(VariableSetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetParameters) DeepCopyInto(out *VariableSetParameters) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = make([]ConnectorParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariable != nil {
		in, out := &in.EnvironmentVariable, &out.EnvironmentVariable
		*out = make([]EnvironmentVariableParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.OrgIDRef != nil {
		in, out := &in.OrgIDRef, &out.OrgIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OrgIDSelector != nil {
		in, out := &in.OrgIDSelector, &out.OrgIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerraformVariable != nil {
		in, out := &in.TerraformVariable, &out.TerraformVariable
		*out = make([]TerraformVariableParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerraformVariableFile != nil {
		in, out := &in.TerraformVariableFile, &out.TerraformVariableFile
		*out = make([]TerraformVariableFileParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetParameters.
func (in *VariableSetParameters) DeepCopy() *VariableSetParameters {
	if in == nil {
		return nil
	}
	out := new(VariableSetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetSpec) DeepCopyInto(out *VariableSetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetSpec.
func (in *VariableSetSpec) DeepCopy() *VariableSetSpec {
	if in == nil {
		return nil
	}
	out := new(VariableSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableSetStatus) DeepCopyInto(out *VariableSetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableSetStatus.
func (in *VariableSetStatus) DeepCopy() *VariableSetStatus {
	if in == nil {
		return nil
	}
	out := new(VariableSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsInitParameters) DeepCopyInto(out *VersionsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsInitParameters.
func (in *VersionsInitParameters) DeepCopy() *VersionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(VersionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsObservation) DeepCopyInto(out *VersionsObservation) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsObservation.
func (in *VersionsObservation) DeepCopy() *VersionsObservation {
	if in == nil {
		return nil
	}
	out := new(VersionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionsParameters) DeepCopyInto(out *VersionsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionsParameters.
func (in *VersionsParameters) DeepCopy() *VersionsParameters {
	if in == nil {
		return nil
	}
	out := new(VersionsParameters)
	in.DeepCopyInto(out)
	return out
}
