apiVersion: harness.harness.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: harness/v1alpha1/user
  labels:
    testing.upbound.io/example-name: john_doe
  name: john-doe
spec:
  forProvider:
    email: john.doe@example.com
    name: John Doe
