// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DashboardFoldersInitParameters struct {

	// (String) Name of the folder.
	// Name of the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type DashboardFoldersObservation struct {

	// (String) Created DateTime of the folder.
	// Created DateTime of the folder.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Identifier of the folder.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the folder.
	// Name of the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type DashboardFoldersParameters struct {

	// (String) Name of the folder.
	// Name of the folder.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// DashboardFoldersSpec defines the desired state of DashboardFolders
type DashboardFoldersSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DashboardFoldersParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DashboardFoldersInitParameters `json:"initProvider,omitempty"`
}

// DashboardFoldersStatus defines the observed state of DashboardFolders.
type DashboardFoldersStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DashboardFoldersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DashboardFolders is the Schema for the DashboardFolderss API. Resource for a Harness Custom Dashboard Folder.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type DashboardFolders struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DashboardFoldersSpec   `json:"spec"`
	Status DashboardFoldersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DashboardFoldersList contains a list of DashboardFolderss
type DashboardFoldersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DashboardFolders `json:"items"`
}

// Repository type metadata.
var (
	DashboardFolders_Kind             = "DashboardFolders"
	DashboardFolders_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DashboardFolders_Kind}.String()
	DashboardFolders_KindAPIVersion   = DashboardFolders_Kind + "." + CRDGroupVersion.String()
	DashboardFolders_GroupVersionKind = CRDGroupVersion.WithKind(DashboardFolders_Kind)
)

func init() {
	SchemeBuilder.Register(&DashboardFolders{}, &DashboardFoldersList{})
}
