// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FileStoreFolderCreatedByInitParameters struct {
}

type FileStoreFolderCreatedByObservation struct {

	// (String)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FileStoreFolderCreatedByParameters struct {
}

type FileStoreFolderInitParameters struct {

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Folder parent identifier on Harness File Store
	// Folder parent identifier on Harness File Store
	ParentIdentifier *string `json:"parentIdentifier,omitempty" tf:"parent_identifier,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FileStoreFolderLastModifiedByInitParameters struct {
}

type FileStoreFolderLastModifiedByObservation struct {

	// (String)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FileStoreFolderLastModifiedByParameters struct {
}

type FileStoreFolderObservation struct {

	// (List of Object) Created by (see below for nested schema)
	// Created by
	CreatedBy []FileStoreFolderCreatedByObservation `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Number) Last modified at
	// Last modified at
	LastModifiedAt *float64 `json:"lastModifiedAt,omitempty" tf:"last_modified_at,omitempty"`

	// (List of Object) Last modified by (see below for nested schema)
	// Last modified by
	LastModifiedBy []FileStoreFolderLastModifiedByObservation `json:"lastModifiedBy,omitempty" tf:"last_modified_by,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Folder parent identifier on Harness File Store
	// Folder parent identifier on Harness File Store
	ParentIdentifier *string `json:"parentIdentifier,omitempty" tf:"parent_identifier,omitempty"`

	// (String) Harness File Store folder path
	// Harness File Store folder path
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FileStoreFolderParameters struct {

	// (String) Description of the resource.
	// Description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Folder parent identifier on Harness File Store
	// Folder parent identifier on Harness File Store
	// +kubebuilder:validation:Optional
	ParentIdentifier *string `json:"parentIdentifier,omitempty" tf:"parent_identifier,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// FileStoreFolderSpec defines the desired state of FileStoreFolder
type FileStoreFolderSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FileStoreFolderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileStoreFolderInitParameters `json:"initProvider,omitempty"`
}

// FileStoreFolderStatus defines the observed state of FileStoreFolder.
type FileStoreFolderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileStoreFolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FileStoreFolder is the Schema for the FileStoreFolders API. Resource for creating folders in Harness.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type FileStoreFolder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentIdentifier) || (has(self.initProvider) && has(self.initProvider.parentIdentifier))",message="spec.forProvider.parentIdentifier is a required parameter"
	Spec   FileStoreFolderSpec   `json:"spec"`
	Status FileStoreFolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileStoreFolderList contains a list of FileStoreFolders
type FileStoreFolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileStoreFolder `json:"items"`
}

// Repository type metadata.
var (
	FileStoreFolder_Kind             = "FileStoreFolder"
	FileStoreFolder_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FileStoreFolder_Kind}.String()
	FileStoreFolder_KindAPIVersion   = FileStoreFolder_Kind + "." + CRDGroupVersion.String()
	FileStoreFolder_GroupVersionKind = CRDGroupVersion.WithKind(FileStoreFolder_Kind)
)

func init() {
	SchemeBuilder.Register(&FileStoreFolder{}, &FileStoreFolderList{})
}
