// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RepoWebhookInitParameters struct {

	// Description of the webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Webhook enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Identifier of the webhook.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// Allow insecure connections for provided webhook URL.
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Identifier of the repository.
	RepoIdentifier *string `json:"repoIdentifier,omitempty" tf:"repo_identifier,omitempty"`

	// Webhook secret which will be used to sign the webhook payload.
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// List of triggers of the webhook (keep empty for all triggers).
	Triggers []*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// URL that's called by the webhook.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RepoWebhookObservation struct {

	// Timestamp when the webhook was created.
	Created *float64 `json:"created,omitempty" tf:"created,omitempty"`

	// ID of the user who created the webhook.
	CreatedBy *float64 `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Description of the webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Webhook enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Created webhook has secret encoding.
	HasSecret *bool `json:"hasSecret,omitempty" tf:"has_secret,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Identifier of the webhook.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// Allow insecure connections for provided webhook URL.
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Identifier of the repository.
	RepoIdentifier *string `json:"repoIdentifier,omitempty" tf:"repo_identifier,omitempty"`

	// List of triggers of the webhook (keep empty for all triggers).
	Triggers []*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// URL that's called by the webhook.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RepoWebhookParameters struct {

	// Description of the webhook.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Webhook enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Identifier of the webhook.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// Allow insecure connections for provided webhook URL.
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Identifier of the repository.
	// +kubebuilder:validation:Optional
	RepoIdentifier *string `json:"repoIdentifier,omitempty" tf:"repo_identifier,omitempty"`

	// Webhook secret which will be used to sign the webhook payload.
	// +kubebuilder:validation:Optional
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// List of triggers of the webhook (keep empty for all triggers).
	// +kubebuilder:validation:Optional
	Triggers []*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// URL that's called by the webhook.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// RepoWebhookSpec defines the desired state of RepoWebhook
type RepoWebhookSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RepoWebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepoWebhookInitParameters `json:"initProvider,omitempty"`
}

// RepoWebhookStatus defines the observed state of RepoWebhook.
type RepoWebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepoWebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepoWebhook is the Schema for the RepoWebhooks API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type RepoWebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.insecure) || (has(self.initProvider) && has(self.initProvider.insecure))",message="spec.forProvider.insecure is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repoIdentifier) || (has(self.initProvider) && has(self.initProvider.repoIdentifier))",message="spec.forProvider.repoIdentifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   RepoWebhookSpec   `json:"spec"`
	Status RepoWebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepoWebhookList contains a list of RepoWebhooks
type RepoWebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepoWebhook `json:"items"`
}

// Repository type metadata.
var (
	RepoWebhook_Kind             = "RepoWebhook"
	RepoWebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepoWebhook_Kind}.String()
	RepoWebhook_KindAPIVersion   = RepoWebhook_Kind + "." + CRDGroupVersion.String()
	RepoWebhook_GroupVersionKind = CRDGroupVersion.WithKind(RepoWebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&RepoWebhook{}, &RepoWebhookList{})
}
