// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type VariablesInitParameters_2 struct {

	// (String) Description of the entity
	// Description of the entity
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the Variable
	// Name of the Variable
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organization Identifier for the Entity
	// Organization Identifier for the Entity
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Project Identifier for the Entity
	// Project Identifier for the Entity
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Block List, Min: 1, Max: 1) List of Spec Fields. (see below for nested schema)
	// List of Spec Fields.
	Spec []VariablesSpecInitParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// (String) Type of Variable
	// Type of Variable
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VariablesObservation_2 struct {

	// (String) Description of the entity
	// Description of the entity
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the Variable
	// Name of the Variable
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organization Identifier for the Entity
	// Organization Identifier for the Entity
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Project Identifier for the Entity
	// Project Identifier for the Entity
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Block List, Min: 1, Max: 1) List of Spec Fields. (see below for nested schema)
	// List of Spec Fields.
	Spec []VariablesSpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// (String) Type of Variable
	// Type of Variable
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VariablesParameters_2 struct {

	// (String) Description of the entity
	// Description of the entity
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Unique identifier of the resource
	// Unique identifier of the resource
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the Variable
	// Name of the Variable
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organization Identifier for the Entity
	// Organization Identifier for the Entity
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Project Identifier for the Entity
	// Project Identifier for the Entity
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/cluster/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Block List, Min: 1, Max: 1) List of Spec Fields. (see below for nested schema)
	// List of Spec Fields.
	// +kubebuilder:validation:Optional
	Spec []VariablesSpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// (String) Type of Variable
	// Type of Variable
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VariablesSpecInitParameters struct {

	// (String) FixedValue of the variable
	// FixedValue of the variable
	FixedValue *string `json:"fixedValue,omitempty" tf:"fixed_value,omitempty"`

	// (String) Type of Value of the Variable. For now only FIXED is supported
	// Type of Value of the Variable. For now only FIXED is supported
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

type VariablesSpecObservation struct {

	// (String) FixedValue of the variable
	// FixedValue of the variable
	FixedValue *string `json:"fixedValue,omitempty" tf:"fixed_value,omitempty"`

	// (String) Type of Value of the Variable. For now only FIXED is supported
	// Type of Value of the Variable. For now only FIXED is supported
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

type VariablesSpecParameters struct {

	// (String) FixedValue of the variable
	// FixedValue of the variable
	// +kubebuilder:validation:Optional
	FixedValue *string `json:"fixedValue" tf:"fixed_value,omitempty"`

	// (String) Type of Value of the Variable. For now only FIXED is supported
	// Type of Value of the Variable. For now only FIXED is supported
	// +kubebuilder:validation:Optional
	ValueType *string `json:"valueType" tf:"value_type,omitempty"`
}

// VariablesSpec defines the desired state of Variables
type VariablesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VariablesParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VariablesInitParameters_2 `json:"initProvider,omitempty"`
}

// VariablesStatus defines the observed state of Variables.
type VariablesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VariablesObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Variables is the Schema for the Variabless API. Resource for creating a Harness Variables.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harness}
type Variables struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spec) || (has(self.initProvider) && has(self.initProvider.spec))",message="spec.forProvider.spec is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   VariablesSpec   `json:"spec"`
	Status VariablesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VariablesList contains a list of Variabless
type VariablesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Variables `json:"items"`
}

// Repository type metadata.
var (
	Variables_Kind             = "Variables"
	Variables_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Variables_Kind}.String()
	Variables_KindAPIVersion   = Variables_Kind + "." + CRDGroupVersion.String()
	Variables_GroupVersionKind = CRDGroupVersion.WithKind(Variables_Kind)
)

func init() {
	SchemeBuilder.Register(&Variables{}, &VariablesList{})
}
