apiVersion: service.harness.crossplane.io/v1alpha1
kind: Helm
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/helm
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    appId: ${harness_application.example.id}
    description: Service for deploying native Helm application.s
    name: helm-example-service

---

apiVersion: harness.harness.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/helm
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
