apiVersion: connector.harness.m.crossplane.io/v1alpha1
kind: Gcp
metadata:
  annotations:
    meta.upbound.io/example-id: connector/v1alpha1/gcp
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    description: test
    identifier: identifier
    manual:
    - delegateSelectors:
      - harness-delegate
      secretKeyRef: account.secret_id
    name: name
    tags:
    - foo:bar
