apiVersion: connector.harness.m.crossplane.io/v1alpha1
kind: GcpSecretManager
metadata:
  annotations:
    meta.upbound.io/example-id: connector/v1alpha1/gcpsecretmanager
  labels:
    testing.upbound.io/example-name: gcp_sm_manual
  name: gcp-sm-manual
  namespace: crossplane-system
spec:
  forProvider:
    credentialsRef: account.${harness_platform_secret_text.test.id}
    delegateSelectors:
    - harness-delegate
    description: test
    identifier: identifier
    name: name
    tags:
    - foo:bar
