apiVersion: connector.harness.m.crossplane.io/v1alpha1
kind: Gitlab
metadata:
  annotations:
    meta.upbound.io/example-id: connector/v1alpha1/gitlab
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    connectionType: Account
    credentials:
    - http:
      - tokenRef: account.secret_id
        username: username
    delegateSelectors:
    - harness-delegate
    description: test
    identifier: identifier
    name: name
    tags:
    - foo:bar
    url: https://gitlab.com/account
    validationRepo: some_repo
