// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ApplicationSpecInitParameters struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for application matching (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// (Block List) List of workloads to include/exclude (see below for nested schema)
	// List of workloads to include/exclude
	Workloads []WorkloadsInitParameters `json:"workloads,omitempty" tf:"workloads,omitempty"`
}

type ApplicationSpecObservation struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for application matching (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// (Block List) List of workloads to include/exclude (see below for nested schema)
	// List of workloads to include/exclude
	Workloads []WorkloadsObservation `json:"workloads,omitempty" tf:"workloads,omitempty"`
}

type ApplicationSpecParameters struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for application matching (EQUAL_TO or NOT_EQUAL_TO)
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`

	// (Block List) List of workloads to include/exclude (see below for nested schema)
	// List of workloads to include/exclude
	// +kubebuilder:validation:Optional
	Workloads []WorkloadsParameters `json:"workloads,omitempty" tf:"workloads,omitempty"`
}

type ChaosServiceAccountSpecInitParameters struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for service account matching (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// (List of String) List of service accounts to include/exclude
	// List of service accounts to include/exclude
	ServiceAccounts []*string `json:"serviceAccounts,omitempty" tf:"service_accounts,omitempty"`
}

type ChaosServiceAccountSpecObservation struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for service account matching (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// (List of String) List of service accounts to include/exclude
	// List of service accounts to include/exclude
	ServiceAccounts []*string `json:"serviceAccounts,omitempty" tf:"service_accounts,omitempty"`
}

type ChaosServiceAccountSpecParameters struct {

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for service account matching (EQUAL_TO or NOT_EQUAL_TO)
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`

	// (List of String) List of service accounts to include/exclude
	// List of service accounts to include/exclude
	// +kubebuilder:validation:Optional
	ServiceAccounts []*string `json:"serviceAccounts" tf:"service_accounts,omitempty"`
}

type FaultSpecFaultsInitParameters struct {

	// (String) Type of the fault (FAULT or FAULT_GROUP)
	// Type of the fault (FAULT or FAULT_GROUP)
	FaultType *string `json:"faultType,omitempty" tf:"fault_type,omitempty"`

	// (String) Name of the security governance condition
	// Name of the fault
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FaultSpecFaultsObservation struct {

	// (String) Type of the fault (FAULT or FAULT_GROUP)
	// Type of the fault (FAULT or FAULT_GROUP)
	FaultType *string `json:"faultType,omitempty" tf:"fault_type,omitempty"`

	// (String) Name of the security governance condition
	// Name of the fault
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FaultSpecFaultsParameters struct {

	// (String) Type of the fault (FAULT or FAULT_GROUP)
	// Type of the fault (FAULT or FAULT_GROUP)
	// +kubebuilder:validation:Optional
	FaultType *string `json:"faultType" tf:"fault_type,omitempty"`

	// (String) Name of the security governance condition
	// Name of the fault
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type FaultSpecInitParameters struct {

	// (Block List, Min: 1) List of fault specifications (see below for nested schema)
	// List of fault specifications
	Faults []FaultSpecFaultsInitParameters `json:"faults,omitempty" tf:"faults,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type FaultSpecObservation struct {

	// (Block List, Min: 1) List of fault specifications (see below for nested schema)
	// List of fault specifications
	Faults []FaultSpecFaultsObservation `json:"faults,omitempty" tf:"faults,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type FaultSpecParameters struct {

	// (Block List, Min: 1) List of fault specifications (see below for nested schema)
	// List of fault specifications
	// +kubebuilder:validation:Optional
	Faults []FaultSpecFaultsParameters `json:"faults" tf:"faults,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`
}

type InfraSpecInitParameters struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	InfraIds []*string `json:"infraIds,omitempty" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type InfraSpecObservation struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	InfraIds []*string `json:"infraIds,omitempty" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type InfraSpecParameters struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	// +kubebuilder:validation:Optional
	InfraIds []*string `json:"infraIds" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`
}

type K8SSpecInitParameters struct {

	// (Block List, Max: 1) Application specification (see below for nested schema)
	// Application specification
	ApplicationSpec []ApplicationSpecInitParameters `json:"applicationSpec,omitempty" tf:"application_spec,omitempty"`

	// (Block List, Max: 1) Chaos service account specification (see below for nested schema)
	// Chaos service account specification
	ChaosServiceAccountSpec []ChaosServiceAccountSpecInitParameters `json:"chaosServiceAccountSpec,omitempty" tf:"chaos_service_account_spec,omitempty"`

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	InfraSpec []InfraSpecInitParameters `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type K8SSpecObservation struct {

	// (Block List, Max: 1) Application specification (see below for nested schema)
	// Application specification
	ApplicationSpec []ApplicationSpecObservation `json:"applicationSpec,omitempty" tf:"application_spec,omitempty"`

	// (Block List, Max: 1) Chaos service account specification (see below for nested schema)
	// Chaos service account specification
	ChaosServiceAccountSpec []ChaosServiceAccountSpecObservation `json:"chaosServiceAccountSpec,omitempty" tf:"chaos_service_account_spec,omitempty"`

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	InfraSpec []InfraSpecObservation `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type K8SSpecParameters struct {

	// (Block List, Max: 1) Application specification (see below for nested schema)
	// Application specification
	// +kubebuilder:validation:Optional
	ApplicationSpec []ApplicationSpecParameters `json:"applicationSpec,omitempty" tf:"application_spec,omitempty"`

	// (Block List, Max: 1) Chaos service account specification (see below for nested schema)
	// Chaos service account specification
	// +kubebuilder:validation:Optional
	ChaosServiceAccountSpec []ChaosServiceAccountSpecParameters `json:"chaosServiceAccountSpec,omitempty" tf:"chaos_service_account_spec,omitempty"`

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	// +kubebuilder:validation:Optional
	InfraSpec []InfraSpecParameters `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type MachineSpecInfraSpecInitParameters struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	InfraIds []*string `json:"infraIds,omitempty" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type MachineSpecInfraSpecObservation struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	InfraIds []*string `json:"infraIds,omitempty" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type MachineSpecInfraSpecParameters struct {

	// (List of String) List of infrastructure IDs to apply the condition to
	// List of infrastructure IDs to apply the condition to
	// +kubebuilder:validation:Optional
	InfraIds []*string `json:"infraIds" tf:"infra_ids,omitempty"`

	// (String) Operator for comparing faults (EQUAL_TO or NOT_EQUAL_TO)
	// Operator for comparing infrastructure IDs (EQUAL_TO or NOT_EQUAL_TO)
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`
}

type MachineSpecInitParameters struct {

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	InfraSpec []MachineSpecInfraSpecInitParameters `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type MachineSpecObservation struct {

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	InfraSpec []MachineSpecInfraSpecObservation `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type MachineSpecParameters struct {

	// (Block List, Max: 1) Infrastructure specification (see below for nested schema)
	// Infrastructure specification
	// +kubebuilder:validation:Optional
	InfraSpec []MachineSpecInfraSpecParameters `json:"infraSpec,omitempty" tf:"infra_spec,omitempty"`
}

type SecurityGovernanceConditionInitParameters struct {

	// (String) Description of the security governance condition
	// Description of the security governance condition
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Min: 1, Max: 1) Specification for faults to be included in the condition (see below for nested schema)
	// Specification for faults to be included in the condition
	FaultSpec []FaultSpecInitParameters `json:"faultSpec,omitempty" tf:"fault_spec,omitempty"`

	// (String) Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	// Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	InfraType *string `json:"infraType,omitempty" tf:"infra_type,omitempty"`

	// (Block List, Max: 1) Kubernetes specific configuration  (see below for nested schema)
	// Kubernetes specific configuration (required when infra_type is KUBERNETES or KUBERNETESV2)
	K8SSpec []K8SSpecInitParameters `json:"k8sSpec,omitempty" tf:"k8s_spec,omitempty"`

	// (Block List, Max: 1) Machine specific configuration  (see below for nested schema)
	// Machine specific configuration (required when infra_type is LINUX or WINDOWS)
	MachineSpec []MachineSpecInitParameters `json:"machineSpec,omitempty" tf:"machine_spec,omitempty"`

	// (String) Name of the security governance condition
	// Name of the security governance condition
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID of the security governance condition
	// The organization ID of the security governance condition
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) The project ID of the security governance condition
	// The project ID of the security governance condition
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) Tags for the security governance condition
	// Tags for the security governance condition
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SecurityGovernanceConditionObservation struct {

	// (String) Description of the security governance condition
	// Description of the security governance condition
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Min: 1, Max: 1) Specification for faults to be included in the condition (see below for nested schema)
	// Specification for faults to be included in the condition
	FaultSpec []FaultSpecObservation `json:"faultSpec,omitempty" tf:"fault_spec,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	// Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	InfraType *string `json:"infraType,omitempty" tf:"infra_type,omitempty"`

	// (Block List, Max: 1) Kubernetes specific configuration  (see below for nested schema)
	// Kubernetes specific configuration (required when infra_type is KUBERNETES or KUBERNETESV2)
	K8SSpec []K8SSpecObservation `json:"k8sSpec,omitempty" tf:"k8s_spec,omitempty"`

	// (Block List, Max: 1) Machine specific configuration  (see below for nested schema)
	// Machine specific configuration (required when infra_type is LINUX or WINDOWS)
	MachineSpec []MachineSpecObservation `json:"machineSpec,omitempty" tf:"machine_spec,omitempty"`

	// (String) Name of the security governance condition
	// Name of the security governance condition
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID of the security governance condition
	// The organization ID of the security governance condition
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The project ID of the security governance condition
	// The project ID of the security governance condition
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) Tags for the security governance condition
	// Tags for the security governance condition
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SecurityGovernanceConditionParameters struct {

	// (String) Description of the security governance condition
	// Description of the security governance condition
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Min: 1, Max: 1) Specification for faults to be included in the condition (see below for nested schema)
	// Specification for faults to be included in the condition
	// +kubebuilder:validation:Optional
	FaultSpec []FaultSpecParameters `json:"faultSpec,omitempty" tf:"fault_spec,omitempty"`

	// (String) Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	// Type of infrastructure (Kubernetes, KubernetesV2, Linux, Windows, CloudFoundry, Container)
	// +kubebuilder:validation:Optional
	InfraType *string `json:"infraType,omitempty" tf:"infra_type,omitempty"`

	// (Block List, Max: 1) Kubernetes specific configuration  (see below for nested schema)
	// Kubernetes specific configuration (required when infra_type is KUBERNETES or KUBERNETESV2)
	// +kubebuilder:validation:Optional
	K8SSpec []K8SSpecParameters `json:"k8sSpec,omitempty" tf:"k8s_spec,omitempty"`

	// (Block List, Max: 1) Machine specific configuration  (see below for nested schema)
	// Machine specific configuration (required when infra_type is LINUX or WINDOWS)
	// +kubebuilder:validation:Optional
	MachineSpec []MachineSpecParameters `json:"machineSpec,omitempty" tf:"machine_spec,omitempty"`

	// (String) Name of the security governance condition
	// Name of the security governance condition
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID of the security governance condition
	// The organization ID of the security governance condition
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) The project ID of the security governance condition
	// The project ID of the security governance condition
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) Tags for the security governance condition
	// Tags for the security governance condition
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type WorkloadsInitParameters struct {

	// (String) ID for the application map
	// ID for the application map
	ApplicationMapID *string `json:"applicationMapId,omitempty" tf:"application_map_id,omitempty"`

	// (String) Kind of the workload (e.g., deployment, statefulset)
	// Kind of the workload (e.g., deployment, statefulset)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Label selector for the workload
	// Label selector for the workload
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) Namespace of the workload
	// Namespace of the workload
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (List of String) List of services associated with the workload
	// List of services associated with the workload
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

type WorkloadsObservation struct {

	// (String) ID for the application map
	// ID for the application map
	ApplicationMapID *string `json:"applicationMapId,omitempty" tf:"application_map_id,omitempty"`

	// (String) Kind of the workload (e.g., deployment, statefulset)
	// Kind of the workload (e.g., deployment, statefulset)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Label selector for the workload
	// Label selector for the workload
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) Namespace of the workload
	// Namespace of the workload
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (List of String) List of services associated with the workload
	// List of services associated with the workload
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

type WorkloadsParameters struct {

	// (String) ID for the application map
	// ID for the application map
	// +kubebuilder:validation:Optional
	ApplicationMapID *string `json:"applicationMapId,omitempty" tf:"application_map_id,omitempty"`

	// (String) Kind of the workload (e.g., deployment, statefulset)
	// Kind of the workload (e.g., deployment, statefulset)
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Label selector for the workload
	// Label selector for the workload
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) Namespace of the workload
	// Namespace of the workload
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace" tf:"namespace,omitempty"`

	// (List of String) List of services associated with the workload
	// List of services associated with the workload
	// +kubebuilder:validation:Optional
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

// SecurityGovernanceConditionSpec defines the desired state of SecurityGovernanceCondition
type SecurityGovernanceConditionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecurityGovernanceConditionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityGovernanceConditionInitParameters `json:"initProvider,omitempty"`
}

// SecurityGovernanceConditionStatus defines the observed state of SecurityGovernanceCondition.
type SecurityGovernanceConditionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityGovernanceConditionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecurityGovernanceCondition is the Schema for the SecurityGovernanceConditions API. Resource for managing a Harness Chaos Security Governance Condition
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type SecurityGovernanceCondition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.faultSpec) || (has(self.initProvider) && has(self.initProvider.faultSpec))",message="spec.forProvider.faultSpec is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.infraType) || (has(self.initProvider) && has(self.initProvider.infraType))",message="spec.forProvider.infraType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SecurityGovernanceConditionSpec   `json:"spec"`
	Status SecurityGovernanceConditionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityGovernanceConditionList contains a list of SecurityGovernanceConditions
type SecurityGovernanceConditionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityGovernanceCondition `json:"items"`
}

// Repository type metadata.
var (
	SecurityGovernanceCondition_Kind             = "SecurityGovernanceCondition"
	SecurityGovernanceCondition_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecurityGovernanceCondition_Kind}.String()
	SecurityGovernanceCondition_KindAPIVersion   = SecurityGovernanceCondition_Kind + "." + CRDGroupVersion.String()
	SecurityGovernanceCondition_GroupVersionKind = CRDGroupVersion.WithKind(SecurityGovernanceCondition_Kind)
)

func init() {
	SchemeBuilder.Register(&SecurityGovernanceCondition{}, &SecurityGovernanceConditionList{})
}
