apiVersion: connector.harness.crossplane.io/v1alpha1
kind: Github
metadata:
  annotations:
    meta.upbound.io/example-id: connector/v1alpha1/github
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    connectionType: Account
    credentials:
    - http:
      - tokenRef: account.secret_id
        username: username
    delegateSelectors:
    - harness-delegate
    description: test
    identifier: identifier
    name: name
    tags:
    - foo:bar
    url: https://github.com/account
    validationRepo: some_repo
