// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GcpCloudCostBillingExportSpecInitParameters struct {

	// (String) Data Set Id.
	// Data Set Id.
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// (String) Table Id.
	// Table Id.
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`
}

type GcpCloudCostBillingExportSpecObservation struct {

	// (String) Data Set Id.
	// Data Set Id.
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// (String) Table Id.
	// Table Id.
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`
}

type GcpCloudCostBillingExportSpecParameters struct {

	// (String) Data Set Id.
	// Data Set Id.
	// +kubebuilder:validation:Optional
	DataSetID *string `json:"dataSetId" tf:"data_set_id,omitempty"`

	// (String) Table Id.
	// Table Id.
	// +kubebuilder:validation:Optional
	TableID *string `json:"tableId" tf:"table_id,omitempty"`
}

type GcpCloudCostInitParameters struct {

	// (Block List, Max: 1) Returns billing details. (see below for nested schema)
	// Returns billing details.
	BillingExportSpec []GcpCloudCostBillingExportSpecInitParameters `json:"billingExportSpec,omitempty" tf:"billing_export_spec,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// +listType=set
	FeaturesEnabled []*string `json:"featuresEnabled,omitempty" tf:"features_enabled,omitempty"`

	// (String) GCP Project Id.
	// GCP Project Id.
	GCPProjectID *string `json:"gcpProjectId,omitempty" tf:"gcp_project_id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Email corresponding to the Service Account.
	// Email corresponding to the Service Account.
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GcpCloudCostObservation struct {

	// (Block List, Max: 1) Returns billing details. (see below for nested schema)
	// Returns billing details.
	BillingExportSpec []GcpCloudCostBillingExportSpecObservation `json:"billingExportSpec,omitempty" tf:"billing_export_spec,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// +listType=set
	FeaturesEnabled []*string `json:"featuresEnabled,omitempty" tf:"features_enabled,omitempty"`

	// (String) GCP Project Id.
	// GCP Project Id.
	GCPProjectID *string `json:"gcpProjectId,omitempty" tf:"gcp_project_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Email corresponding to the Service Account.
	// Email corresponding to the Service Account.
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GcpCloudCostParameters struct {

	// (Block List, Max: 1) Returns billing details. (see below for nested schema)
	// Returns billing details.
	// +kubebuilder:validation:Optional
	BillingExportSpec []GcpCloudCostBillingExportSpecParameters `json:"billingExportSpec,omitempty" tf:"billing_export_spec,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// Indicates which features to enable among Billing, Optimization, Visibility and Governance.
	// +kubebuilder:validation:Optional
	// +listType=set
	FeaturesEnabled []*string `json:"featuresEnabled,omitempty" tf:"features_enabled,omitempty"`

	// (String) GCP Project Id.
	// GCP Project Id.
	// +kubebuilder:validation:Optional
	GCPProjectID *string `json:"gcpProjectId,omitempty" tf:"gcp_project_id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Email corresponding to the Service Account.
	// Email corresponding to the Service Account.
	// +kubebuilder:validation:Optional
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// GcpCloudCostSpec defines the desired state of GcpCloudCost
type GcpCloudCostSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GcpCloudCostParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GcpCloudCostInitParameters `json:"initProvider,omitempty"`
}

// GcpCloudCostStatus defines the observed state of GcpCloudCost.
type GcpCloudCostStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GcpCloudCostObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GcpCloudCost is the Schema for the GcpCloudCosts API. Resource for creating a GCP Cloud Cost connector in Harness.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type GcpCloudCost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.featuresEnabled) || (has(self.initProvider) && has(self.initProvider.featuresEnabled))",message="spec.forProvider.featuresEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpProjectId) || (has(self.initProvider) && has(self.initProvider.gcpProjectId))",message="spec.forProvider.gcpProjectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceAccountEmail) || (has(self.initProvider) && has(self.initProvider.serviceAccountEmail))",message="spec.forProvider.serviceAccountEmail is a required parameter"
	Spec   GcpCloudCostSpec   `json:"spec"`
	Status GcpCloudCostStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GcpCloudCostList contains a list of GcpCloudCosts
type GcpCloudCostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GcpCloudCost `json:"items"`
}

// Repository type metadata.
var (
	GcpCloudCost_Kind             = "GcpCloudCost"
	GcpCloudCost_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GcpCloudCost_Kind}.String()
	GcpCloudCost_KindAPIVersion   = GcpCloudCost_Kind + "." + CRDGroupVersion.String()
	GcpCloudCost_GroupVersionKind = CRDGroupVersion.WithKind(GcpCloudCost_Kind)
)

func init() {
	SchemeBuilder.Register(&GcpCloudCost{}, &GcpCloudCostList{})
}
