// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PrometheusHeadersInitParameters struct {

	// (String) Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	EncryptedValueRef *string `json:"encryptedValueRef,omitempty" tf:"encrypted_value_ref,omitempty"`

	// (String) Key.
	// Key.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Value.
	// Value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (Boolean) Encrypted value.
	// Encrypted value.
	ValueEncrypted *bool `json:"valueEncrypted,omitempty" tf:"value_encrypted,omitempty"`
}

type PrometheusHeadersObservation struct {

	// (String) Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	EncryptedValueRef *string `json:"encryptedValueRef,omitempty" tf:"encrypted_value_ref,omitempty"`

	// (String) Key.
	// Key.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Value.
	// Value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (Boolean) Encrypted value.
	// Encrypted value.
	ValueEncrypted *bool `json:"valueEncrypted,omitempty" tf:"value_encrypted,omitempty"`
}

type PrometheusHeadersParameters struct {

	// (String) Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the encrypted value. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// +kubebuilder:validation:Optional
	EncryptedValueRef *string `json:"encryptedValueRef,omitempty" tf:"encrypted_value_ref,omitempty"`

	// (String) Key.
	// Key.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String) Value.
	// Value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (Boolean) Encrypted value.
	// Encrypted value.
	// +kubebuilder:validation:Optional
	ValueEncrypted *bool `json:"valueEncrypted,omitempty" tf:"value_encrypted,omitempty"`
}

type PrometheusInitParameters struct {

	// (Set of String) Tags to filter delegates for connection.
	// Tags to filter delegates for connection.
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set) Headers. (see below for nested schema)
	// Headers.
	Headers []PrometheusHeadersInitParameters `json:"headers,omitempty" tf:"headers,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	PasswordRef *string `json:"passwordRef,omitempty" tf:"password_ref,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) URL of the Prometheus server.
	// URL of the Prometheus server.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) User name.
	// User name.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type PrometheusObservation struct {

	// (Set of String) Tags to filter delegates for connection.
	// Tags to filter delegates for connection.
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set) Headers. (see below for nested schema)
	// Headers.
	Headers []PrometheusHeadersObservation `json:"headers,omitempty" tf:"headers,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	PasswordRef *string `json:"passwordRef,omitempty" tf:"password_ref,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) URL of the Prometheus server.
	// URL of the Prometheus server.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) User name.
	// User name.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type PrometheusParameters struct {

	// (Set of String) Tags to filter delegates for connection.
	// Tags to filter delegates for connection.
	// +kubebuilder:validation:Optional
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set) Headers. (see below for nested schema)
	// Headers.
	// +kubebuilder:validation:Optional
	Headers []PrometheusHeadersParameters `json:"headers,omitempty" tf:"headers,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// Reference to the Harness secret containing the password. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
	// +kubebuilder:validation:Optional
	PasswordRef *string `json:"passwordRef,omitempty" tf:"password_ref,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) URL of the Prometheus server.
	// URL of the Prometheus server.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) User name.
	// User name.
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

// PrometheusSpec defines the desired state of Prometheus
type PrometheusSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PrometheusParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrometheusInitParameters `json:"initProvider,omitempty"`
}

// PrometheusStatus defines the observed state of Prometheus.
type PrometheusStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrometheusObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Prometheus is the Schema for the Prometheuss API. Resource for creating a Prometheus connector.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type Prometheus struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   PrometheusSpec   `json:"spec"`
	Status PrometheusStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrometheusList contains a list of Prometheuss
type PrometheusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Prometheus `json:"items"`
}

// Repository type metadata.
var (
	Prometheus_Kind             = "Prometheus"
	Prometheus_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Prometheus_Kind}.String()
	Prometheus_KindAPIVersion   = Prometheus_Kind + "." + CRDGroupVersion.String()
	Prometheus_GroupVersionKind = CRDGroupVersion.WithKind(Prometheus_Kind)
)

func init() {
	SchemeBuilder.Register(&Prometheus{}, &PrometheusList{})
}
