// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VaultInitParameters struct {

	// (String) Access type.
	// Access type.
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// (String) ID of App Role.
	// ID of App Role.
	AppRoleID *string `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (String) Authentication token for Vault.
	// Authentication token for Vault.
	AuthToken *string `json:"authToken,omitempty" tf:"auth_token,omitempty"`

	// (String) AWS region where the AWS IAM authentication will happen.
	// AWS region where the AWS IAM authentication will happen.
	AwsRegion *string `json:"awsRegion,omitempty" tf:"aws_region,omitempty"`

	// (String) Location of the Vault directory where the secret will be stored.
	// Location of the Vault directory where the secret will be stored.
	BasePath *string `json:"basePath,omitempty" tf:"base_path,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Set of String) List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Execute on delegate or not.
	// Execute on delegate or not.
	ExecuteOnDelegate *bool `json:"executeOnDelegate,omitempty" tf:"execute_on_delegate,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (Boolean) Read only or not.
	// Read only or not.
	IsReadOnly *bool `json:"isReadOnly,omitempty" tf:"is_read_only,omitempty"`

	// (String) The path where Kubernetes Auth is enabled in Vault.
	// The path where Kubernetes Auth is enabled in Vault.
	K8SAuthEndpoint *string `json:"k8sAuthEndpoint,omitempty" tf:"k8s_auth_endpoint,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Vault namespace where the Secret will be created.
	// Vault namespace where the Secret will be created.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Boolean) Read only.
	// Read only.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Boolean value to indicate if AppRole token renewal is enabled or not.
	// Boolean value to indicate if AppRole token renewal is enabled or not.
	RenewAppRoleToken *bool `json:"renewAppRoleToken,omitempty" tf:"renew_app_role_token,omitempty"`

	// (Number) The time interval for the token renewal.
	// The time interval for the token renewal.
	RenewalIntervalMinutes *float64 `json:"renewalIntervalMinutes,omitempty" tf:"renewal_interval_minutes,omitempty"`

	// (Boolean) Manually entered Secret Engine.
	// Manually entered Secret Engine.
	SecretEngineManuallyConfigured *bool `json:"secretEngineManuallyConfigured,omitempty" tf:"secret_engine_manually_configured,omitempty"`

	// (String) Name of the Secret Engine.
	// Name of the Secret Engine.
	SecretEngineName *string `json:"secretEngineName,omitempty" tf:"secret_engine_name,omitempty"`

	// (Number) Version of Secret Engine.
	// Version of Secret Engine.
	SecretEngineVersion *float64 `json:"secretEngineVersion,omitempty" tf:"secret_engine_version,omitempty"`

	// (String) ID of the Secret.
	// ID of the Secret.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The Service Account token path in the K8s pod where the token is mounted.
	// The Service Account token path in the K8s pod where the token is mounted.
	ServiceAccountTokenPath *string `json:"serviceAccountTokenPath,omitempty" tf:"service_account_token_path,omitempty"`

	// (String) The location from which the authentication token should be read.
	// The location from which the authentication token should be read.
	SinkPath *string `json:"sinkPath,omitempty" tf:"sink_path,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Boolean) Boolean value to indicate if AWS IAM is used for authentication.
	// Boolean value to indicate if AWS IAM is used for authentication.
	UseAwsIAM *bool `json:"useAwsIam,omitempty" tf:"use_aws_iam,omitempty"`

	// (Boolean) Boolean value to indicate if JWT is used for authentication.
	// Boolean value to indicate if JWT is used for authentication.
	UseJwtAuth *bool `json:"useJwtAuth,omitempty" tf:"use_jwt_auth,omitempty"`

	// (Boolean) Boolean value to indicate if K8s Auth is used for authentication.
	// Boolean value to indicate if K8s Auth is used for authentication.
	UseK8SAuth *bool `json:"useK8SAuth,omitempty" tf:"use_k8s_auth,omitempty"`

	// (Boolean) Boolean value to indicate if Vault Agent is used for authentication.
	// Boolean value to indicate if Vault Agent is used for authentication.
	UseVaultAgent *bool `json:"useVaultAgent,omitempty" tf:"use_vault_agent,omitempty"`

	// (String) The Vault role defined to bind to aws iam account/role being accessed.
	// The Vault role defined to bind to aws iam account/role being accessed.
	VaultAwsIAMRole *string `json:"vaultAwsIamRole,omitempty" tf:"vault_aws_iam_role,omitempty"`

	// (String) Custom path at with JWT auth in enabled for Vault
	// Custom path at with JWT auth in enabled for Vault
	VaultJwtAuthPath *string `json:"vaultJwtAuthPath,omitempty" tf:"vault_jwt_auth_path,omitempty"`

	// (String) The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	// The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	VaultJwtAuthRole *string `json:"vaultJwtAuthRole,omitempty" tf:"vault_jwt_auth_role,omitempty"`

	// (String) The role where K8s Auth will happen.
	// The role where K8s Auth will happen.
	VaultK8SAuthRole *string `json:"vaultK8SAuthRole,omitempty" tf:"vault_k8s_auth_role,omitempty"`

	// (String) URL of the HashiCorp Vault.
	// URL of the HashiCorp Vault.
	VaultURL *string `json:"vaultUrl,omitempty" tf:"vault_url,omitempty"`

	// (String) The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	// The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	XvaultAwsIAMServerID *string `json:"xvaultAwsIamServerId,omitempty" tf:"xvault_aws_iam_server_id,omitempty"`
}

type VaultObservation struct {

	// (String) Access type.
	// Access type.
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// (String) ID of App Role.
	// ID of App Role.
	AppRoleID *string `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (String) Authentication token for Vault.
	// Authentication token for Vault.
	AuthToken *string `json:"authToken,omitempty" tf:"auth_token,omitempty"`

	// (String) AWS region where the AWS IAM authentication will happen.
	// AWS region where the AWS IAM authentication will happen.
	AwsRegion *string `json:"awsRegion,omitempty" tf:"aws_region,omitempty"`

	// (String) Location of the Vault directory where the secret will be stored.
	// Location of the Vault directory where the secret will be stored.
	BasePath *string `json:"basePath,omitempty" tf:"base_path,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Set of String) List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Execute on delegate or not.
	// Execute on delegate or not.
	ExecuteOnDelegate *bool `json:"executeOnDelegate,omitempty" tf:"execute_on_delegate,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (Boolean) Read only or not.
	// Read only or not.
	IsReadOnly *bool `json:"isReadOnly,omitempty" tf:"is_read_only,omitempty"`

	// (String) The path where Kubernetes Auth is enabled in Vault.
	// The path where Kubernetes Auth is enabled in Vault.
	K8SAuthEndpoint *string `json:"k8sAuthEndpoint,omitempty" tf:"k8s_auth_endpoint,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Vault namespace where the Secret will be created.
	// Vault namespace where the Secret will be created.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) Read only.
	// Read only.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Boolean value to indicate if AppRole token renewal is enabled or not.
	// Boolean value to indicate if AppRole token renewal is enabled or not.
	RenewAppRoleToken *bool `json:"renewAppRoleToken,omitempty" tf:"renew_app_role_token,omitempty"`

	// (Number) The time interval for the token renewal.
	// The time interval for the token renewal.
	RenewalIntervalMinutes *float64 `json:"renewalIntervalMinutes,omitempty" tf:"renewal_interval_minutes,omitempty"`

	// (Boolean) Manually entered Secret Engine.
	// Manually entered Secret Engine.
	SecretEngineManuallyConfigured *bool `json:"secretEngineManuallyConfigured,omitempty" tf:"secret_engine_manually_configured,omitempty"`

	// (String) Name of the Secret Engine.
	// Name of the Secret Engine.
	SecretEngineName *string `json:"secretEngineName,omitempty" tf:"secret_engine_name,omitempty"`

	// (Number) Version of Secret Engine.
	// Version of Secret Engine.
	SecretEngineVersion *float64 `json:"secretEngineVersion,omitempty" tf:"secret_engine_version,omitempty"`

	// (String) ID of the Secret.
	// ID of the Secret.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The Service Account token path in the K8s pod where the token is mounted.
	// The Service Account token path in the K8s pod where the token is mounted.
	ServiceAccountTokenPath *string `json:"serviceAccountTokenPath,omitempty" tf:"service_account_token_path,omitempty"`

	// (String) The location from which the authentication token should be read.
	// The location from which the authentication token should be read.
	SinkPath *string `json:"sinkPath,omitempty" tf:"sink_path,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Boolean) Boolean value to indicate if AWS IAM is used for authentication.
	// Boolean value to indicate if AWS IAM is used for authentication.
	UseAwsIAM *bool `json:"useAwsIam,omitempty" tf:"use_aws_iam,omitempty"`

	// (Boolean) Boolean value to indicate if JWT is used for authentication.
	// Boolean value to indicate if JWT is used for authentication.
	UseJwtAuth *bool `json:"useJwtAuth,omitempty" tf:"use_jwt_auth,omitempty"`

	// (Boolean) Boolean value to indicate if K8s Auth is used for authentication.
	// Boolean value to indicate if K8s Auth is used for authentication.
	UseK8SAuth *bool `json:"useK8SAuth,omitempty" tf:"use_k8s_auth,omitempty"`

	// (Boolean) Boolean value to indicate if Vault Agent is used for authentication.
	// Boolean value to indicate if Vault Agent is used for authentication.
	UseVaultAgent *bool `json:"useVaultAgent,omitempty" tf:"use_vault_agent,omitempty"`

	// (String) The Vault role defined to bind to aws iam account/role being accessed.
	// The Vault role defined to bind to aws iam account/role being accessed.
	VaultAwsIAMRole *string `json:"vaultAwsIamRole,omitempty" tf:"vault_aws_iam_role,omitempty"`

	// (String) Custom path at with JWT auth in enabled for Vault
	// Custom path at with JWT auth in enabled for Vault
	VaultJwtAuthPath *string `json:"vaultJwtAuthPath,omitempty" tf:"vault_jwt_auth_path,omitempty"`

	// (String) The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	// The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	VaultJwtAuthRole *string `json:"vaultJwtAuthRole,omitempty" tf:"vault_jwt_auth_role,omitempty"`

	// (String) The role where K8s Auth will happen.
	// The role where K8s Auth will happen.
	VaultK8SAuthRole *string `json:"vaultK8SAuthRole,omitempty" tf:"vault_k8s_auth_role,omitempty"`

	// (String) URL of the HashiCorp Vault.
	// URL of the HashiCorp Vault.
	VaultURL *string `json:"vaultUrl,omitempty" tf:"vault_url,omitempty"`

	// (String) The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	// The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	XvaultAwsIAMServerID *string `json:"xvaultAwsIamServerId,omitempty" tf:"xvault_aws_iam_server_id,omitempty"`
}

type VaultParameters struct {

	// (String) Access type.
	// Access type.
	// +kubebuilder:validation:Optional
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// (String) ID of App Role.
	// ID of App Role.
	// +kubebuilder:validation:Optional
	AppRoleID *string `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (String) Authentication token for Vault.
	// Authentication token for Vault.
	// +kubebuilder:validation:Optional
	AuthToken *string `json:"authToken,omitempty" tf:"auth_token,omitempty"`

	// (String) AWS region where the AWS IAM authentication will happen.
	// AWS region where the AWS IAM authentication will happen.
	// +kubebuilder:validation:Optional
	AwsRegion *string `json:"awsRegion,omitempty" tf:"aws_region,omitempty"`

	// (String) Location of the Vault directory where the secret will be stored.
	// Location of the Vault directory where the secret will be stored.
	// +kubebuilder:validation:Optional
	BasePath *string `json:"basePath,omitempty" tf:"base_path,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	// +kubebuilder:validation:Optional
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Set of String) List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// List of Delegate Selectors that belong to the same Delegate and are used to connect to the Secret Manager.
	// +kubebuilder:validation:Optional
	// +listType=set
	DelegateSelectors []*string `json:"delegateSelectors,omitempty" tf:"delegate_selectors,omitempty"`

	// (String) Description of the resource.
	// Description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Execute on delegate or not.
	// Execute on delegate or not.
	// +kubebuilder:validation:Optional
	ExecuteOnDelegate *bool `json:"executeOnDelegate,omitempty" tf:"execute_on_delegate,omitempty"`

	// (String) Unique identifier of the resource.
	// Unique identifier of the resource.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Boolean) Is default or not.
	// Is default or not.
	// +kubebuilder:validation:Optional
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (Boolean) Read only or not.
	// Read only or not.
	// +kubebuilder:validation:Optional
	IsReadOnly *bool `json:"isReadOnly,omitempty" tf:"is_read_only,omitempty"`

	// (String) The path where Kubernetes Auth is enabled in Vault.
	// The path where Kubernetes Auth is enabled in Vault.
	// +kubebuilder:validation:Optional
	K8SAuthEndpoint *string `json:"k8sAuthEndpoint,omitempty" tf:"k8s_auth_endpoint,omitempty"`

	// (String) Name of the resource.
	// Name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Vault namespace where the Secret will be created.
	// Vault namespace where the Secret will be created.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) Unique identifier of the organization.
	// Unique identifier of the organization.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in platform to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) Unique identifier of the project.
	// Unique identifier of the project.
	// +crossplane:generate:reference:type=github.com/terasky-oss/provider-harness/apis/namespaced/platform/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("identifier",false)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in platform to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Boolean) Read only.
	// Read only.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Boolean value to indicate if AppRole token renewal is enabled or not.
	// Boolean value to indicate if AppRole token renewal is enabled or not.
	// +kubebuilder:validation:Optional
	RenewAppRoleToken *bool `json:"renewAppRoleToken,omitempty" tf:"renew_app_role_token,omitempty"`

	// (Number) The time interval for the token renewal.
	// The time interval for the token renewal.
	// +kubebuilder:validation:Optional
	RenewalIntervalMinutes *float64 `json:"renewalIntervalMinutes,omitempty" tf:"renewal_interval_minutes,omitempty"`

	// (Boolean) Manually entered Secret Engine.
	// Manually entered Secret Engine.
	// +kubebuilder:validation:Optional
	SecretEngineManuallyConfigured *bool `json:"secretEngineManuallyConfigured,omitempty" tf:"secret_engine_manually_configured,omitempty"`

	// (String) Name of the Secret Engine.
	// Name of the Secret Engine.
	// +kubebuilder:validation:Optional
	SecretEngineName *string `json:"secretEngineName,omitempty" tf:"secret_engine_name,omitempty"`

	// (Number) Version of Secret Engine.
	// Version of Secret Engine.
	// +kubebuilder:validation:Optional
	SecretEngineVersion *float64 `json:"secretEngineVersion,omitempty" tf:"secret_engine_version,omitempty"`

	// (String) ID of the Secret.
	// ID of the Secret.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The Service Account token path in the K8s pod where the token is mounted.
	// The Service Account token path in the K8s pod where the token is mounted.
	// +kubebuilder:validation:Optional
	ServiceAccountTokenPath *string `json:"serviceAccountTokenPath,omitempty" tf:"service_account_token_path,omitempty"`

	// (String) The location from which the authentication token should be read.
	// The location from which the authentication token should be read.
	// +kubebuilder:validation:Optional
	SinkPath *string `json:"sinkPath,omitempty" tf:"sink_path,omitempty"`

	// (Set of String) Tags to associate with the resource.
	// Tags to associate with the resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Boolean) Boolean value to indicate if AWS IAM is used for authentication.
	// Boolean value to indicate if AWS IAM is used for authentication.
	// +kubebuilder:validation:Optional
	UseAwsIAM *bool `json:"useAwsIam,omitempty" tf:"use_aws_iam,omitempty"`

	// (Boolean) Boolean value to indicate if JWT is used for authentication.
	// Boolean value to indicate if JWT is used for authentication.
	// +kubebuilder:validation:Optional
	UseJwtAuth *bool `json:"useJwtAuth,omitempty" tf:"use_jwt_auth,omitempty"`

	// (Boolean) Boolean value to indicate if K8s Auth is used for authentication.
	// Boolean value to indicate if K8s Auth is used for authentication.
	// +kubebuilder:validation:Optional
	UseK8SAuth *bool `json:"useK8SAuth,omitempty" tf:"use_k8s_auth,omitempty"`

	// (Boolean) Boolean value to indicate if Vault Agent is used for authentication.
	// Boolean value to indicate if Vault Agent is used for authentication.
	// +kubebuilder:validation:Optional
	UseVaultAgent *bool `json:"useVaultAgent,omitempty" tf:"use_vault_agent,omitempty"`

	// (String) The Vault role defined to bind to aws iam account/role being accessed.
	// The Vault role defined to bind to aws iam account/role being accessed.
	// +kubebuilder:validation:Optional
	VaultAwsIAMRole *string `json:"vaultAwsIamRole,omitempty" tf:"vault_aws_iam_role,omitempty"`

	// (String) Custom path at with JWT auth in enabled for Vault
	// Custom path at with JWT auth in enabled for Vault
	// +kubebuilder:validation:Optional
	VaultJwtAuthPath *string `json:"vaultJwtAuthPath,omitempty" tf:"vault_jwt_auth_path,omitempty"`

	// (String) The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	// The Vault role defined with JWT auth type for accessing Vault as per policies binded.
	// +kubebuilder:validation:Optional
	VaultJwtAuthRole *string `json:"vaultJwtAuthRole,omitempty" tf:"vault_jwt_auth_role,omitempty"`

	// (String) The role where K8s Auth will happen.
	// The role where K8s Auth will happen.
	// +kubebuilder:validation:Optional
	VaultK8SAuthRole *string `json:"vaultK8SAuthRole,omitempty" tf:"vault_k8s_auth_role,omitempty"`

	// (String) URL of the HashiCorp Vault.
	// URL of the HashiCorp Vault.
	// +kubebuilder:validation:Optional
	VaultURL *string `json:"vaultUrl,omitempty" tf:"vault_url,omitempty"`

	// (String) The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	// The AWS IAM Header Server ID that has been configured for this AWS IAM instance.
	// +kubebuilder:validation:Optional
	XvaultAwsIAMServerID *string `json:"xvaultAwsIamServerId,omitempty" tf:"xvault_aws_iam_server_id,omitempty"`
}

// VaultSpec defines the desired state of Vault
type VaultSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VaultParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VaultInitParameters `json:"initProvider,omitempty"`
}

// VaultStatus defines the observed state of Vault.
type VaultStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vault is the Schema for the Vaults API. Resource for creating a HashiCorp Vault Secret Manager connector.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,harness}
type Vault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.identifier) || (has(self.initProvider) && has(self.initProvider.identifier))",message="spec.forProvider.identifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.renewalIntervalMinutes) || (has(self.initProvider) && has(self.initProvider.renewalIntervalMinutes))",message="spec.forProvider.renewalIntervalMinutes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vaultUrl) || (has(self.initProvider) && has(self.initProvider.vaultUrl))",message="spec.forProvider.vaultUrl is a required parameter"
	Spec   VaultSpec   `json:"spec"`
	Status VaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VaultList contains a list of Vaults
type VaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vault `json:"items"`
}

// Repository type metadata.
var (
	Vault_Kind             = "Vault"
	Vault_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vault_Kind}.String()
	Vault_KindAPIVersion   = Vault_Kind + "." + CRDGroupVersion.String()
	Vault_GroupVersionKind = CRDGroupVersion.WithKind(Vault_Kind)
)

func init() {
	SchemeBuilder.Register(&Vault{}, &VaultList{})
}
