apiVersion: platform.harness.m.crossplane.io/v1alpha1
kind: GitxWebhook
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/gitxwebhook
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    connectorRef: connectorRef
    identifier: webhook Identifier
    name: webhook name
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    repoName: repo name
