apiVersion: platform.harness.m.crossplane.io/v1alpha1
kind: ManualFreeze
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/manualfreeze
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    accountId: accountIdentifier
    identifier: identifier
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    yaml: |
      freeze:
        name: freezeName
        identifier: identifier
        entityConfigs:
          - name: r1
            entities:
              - filterType: All
                type: Org
              - filterType: All
                type: Project
              - filterType: All
                type: Service
              - filterType: All
                type: EnvType
        status: Disabled
        description: hi
        windows:
        - timeZone: Asia/Calcutta
          startTime: 2023-05-03 04:16 PM
          duration: 30m
          recurrence:
            type: Daily
        notificationRules: []
        tags: {}
