apiVersion: platform.harness.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    description: ${harness_platform_policy.test.description}
    gitBaseBranch: ${harness_platform_policy.test.git_base_branch}
    gitBranch: ${harness_platform_policy.test.git_branch}
    gitCommitMsg: ${harness_platform_policy.test.git_commit_msg}
    gitConnectorRef: ${harness_platform_policy.test.git_connector_ref}
    gitImport: false
    gitIsNewBranch: false
    gitPath: ${harness_platform_policy.test.git_path}
    gitRepo: ${harness_platform_policy.test.git_repo}
    identifier: ${harness_platform_policy.test.identifier}
    name: ${harness_platform_policy.test.name}
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    rego: |
      package pipeline

      # Deny pipelines that don't have an approval step
      # NOTE: Try removing the HarnessApproval step from your input to see the policy fail
      deny[msg] {
          # Find all stages that are Deployments ...
          input.pipeline.stages[i].stage.type == "Approval"

          # ... that are not in the set of stages with HarnessApproval steps
          not stages_with_approval[i]

          # Show a human-friendly error message
          msg := sprintf("Approval stage '%s' does not have a HarnessApproval step", [input.pipeline.stages[i].stage.name])
      }

      # Find the set of stages that contain a HarnessApproval step
      stages_with_approval[i] {
          input.pipeline.stages[i].stage.spec.execution.steps[_].step.type == "HarnessApproval"
      }
