apiVersion: platform.harness.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/project
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    color: '#0063F7'
    identifier: shemerlovesbibi
    name: Shemer Loves Bibi
    orgId: default
