apiVersion: platform.harness.m.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: platform/v1alpha1/token
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    accountId: account_id
    apikeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    apikeyType: USER
    identifier: test_token
    name: test token
    parentId: apikey_parent_id
